# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from cdx_client.models.device_summary import DeviceSummary
from cdx_client.models.iso_build_summary import IsoBuildSummary
from cdx_client.models.server_summary import ServerSummary
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class DashboardResponse(BaseModel):
    """
    DashboardResponse
    """ # noqa: E501
    devices: Optional[DeviceSummary] = None
    iso_builds: Optional[IsoBuildSummary] = None
    server: Optional[ServerSummary] = None
    __properties: ClassVar[List[str]] = ["devices", "iso_builds", "server"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DashboardResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of devices
        if self.devices:
            _dict['devices'] = self.devices.to_dict()
        # override the default output from pydantic by calling `to_dict()` of iso_builds
        if self.iso_builds:
            _dict['iso_builds'] = self.iso_builds.to_dict()
        # override the default output from pydantic by calling `to_dict()` of server
        if self.server:
            _dict['server'] = self.server.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DashboardResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "devices": DeviceSummary.from_dict(obj["devices"]) if obj.get("devices") is not None else None,
            "iso_builds": IsoBuildSummary.from_dict(obj["iso_builds"]) if obj.get("iso_builds") is not None else None,
            "server": ServerSummary.from_dict(obj["server"]) if obj.get("server") is not None else None
        })
        return _obj


