# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IsoBuildJobResponse(BaseModel):
    """
    IsoBuildJobResponse
    """ # noqa: E501
    id: StrictStr
    profile: StrictStr
    requested_by: StrictStr
    status: StrictStr
    git_ref: StrictStr
    started_at: Optional[datetime]
    finished_at: Optional[datetime]
    iso_path: Optional[StrictStr]
    iso_sha256: Optional[StrictStr]
    iso_size_bytes: Optional[StrictInt]
    log_path: Optional[StrictStr]
    error_message: Optional[StrictStr]
    notes: Optional[StrictStr]
    created_at: datetime
    __properties: ClassVar[List[str]] = ["id", "profile", "requested_by", "status", "git_ref", "started_at", "finished_at", "iso_path", "iso_sha256", "iso_size_bytes", "log_path", "error_message", "notes", "created_at"]

    @field_validator('profile')
    def profile_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['admin', 'standard', 'field', 'kiosk', 'admin-support']):
            raise ValueError("must be one of enum values ('admin', 'standard', 'field', 'kiosk', 'admin-support')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['queued', 'running', 'succeeded', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('queued', 'running', 'succeeded', 'failed', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IsoBuildJobResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if finished_at (nullable) is None
        # and model_fields_set contains the field
        if self.finished_at is None and "finished_at" in self.model_fields_set:
            _dict['finished_at'] = None

        # set to None if iso_path (nullable) is None
        # and model_fields_set contains the field
        if self.iso_path is None and "iso_path" in self.model_fields_set:
            _dict['iso_path'] = None

        # set to None if iso_sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.iso_sha256 is None and "iso_sha256" in self.model_fields_set:
            _dict['iso_sha256'] = None

        # set to None if iso_size_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.iso_size_bytes is None and "iso_size_bytes" in self.model_fields_set:
            _dict['iso_size_bytes'] = None

        # set to None if log_path (nullable) is None
        # and model_fields_set contains the field
        if self.log_path is None and "log_path" in self.model_fields_set:
            _dict['log_path'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['error_message'] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IsoBuildJobResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "profile": obj.get("profile"),
            "requested_by": obj.get("requested_by"),
            "status": obj.get("status"),
            "git_ref": obj.get("git_ref"),
            "started_at": obj.get("started_at"),
            "finished_at": obj.get("finished_at"),
            "iso_path": obj.get("iso_path"),
            "iso_sha256": obj.get("iso_sha256"),
            "iso_size_bytes": obj.get("iso_size_bytes"),
            "log_path": obj.get("log_path"),
            "error_message": obj.get("error_message"),
            "notes": obj.get("notes"),
            "created_at": obj.get("created_at")
        })
        return _obj


