# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PolicyResponse(BaseModel):
    """
    PolicyResponse
    """ # noqa: E501
    profile: StrictStr
    update_ring: StrictStr
    heartbeat_interval_seconds: Annotated[int, Field(le=86400, strict=True, ge=10)]
    inventory_interval_seconds: Annotated[int, Field(le=86400, strict=True, ge=60)]
    policy_version: Annotated[int, Field(strict=True, ge=1)]
    __properties: ClassVar[List[str]] = ["profile", "update_ring", "heartbeat_interval_seconds", "inventory_interval_seconds", "policy_version"]

    @field_validator('profile')
    def profile_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['standard', 'field', 'kiosk']):
            raise ValueError("must be one of enum values ('standard', 'field', 'kiosk')")
        return value

    @field_validator('update_ring')
    def update_ring_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['ring0', 'ring1', 'ring2', 'ring3']):
            raise ValueError("must be one of enum values ('ring0', 'ring1', 'ring2', 'ring3')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PolicyResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PolicyResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "profile": obj.get("profile"),
            "update_ring": obj.get("update_ring"),
            "heartbeat_interval_seconds": obj.get("heartbeat_interval_seconds"),
            "inventory_interval_seconds": obj.get("inventory_interval_seconds"),
            "policy_version": obj.get("policy_version")
        })
        return _obj


