# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cdx_client.models.pxe_rollback_pattern import PXERollbackPattern
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PXERollbackRequest(BaseModel):
    """
    Operator-initiated rollback request (from Admin WebUI or CLI).
    """ # noqa: E501
    pattern: PXERollbackPattern
    reason: Annotated[str, Field(min_length=10, strict=True, max_length=500)] = Field(description="Reason for rollback (audit trail).")
    target_version: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    profile: Optional[Annotated[str, Field(strict=True)]] = None
    ring: Optional[Annotated[str, Field(strict=True)]] = None
    site: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    device_mac: Optional[Annotated[str, Field(strict=True, max_length=17)]] = None
    backup_pxe_ip: Optional[Annotated[str, Field(strict=True, max_length=45)]] = None
    __properties: ClassVar[List[str]] = ["pattern", "reason", "target_version", "profile", "ring", "site", "device_mac", "backup_pxe_ip"]

    @field_validator('profile')
    def profile_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(standard|field|kiosk)$", value):
            raise ValueError(r"must validate the regular expression /^(standard|field|kiosk)$/")
        return value

    @field_validator('ring')
    def ring_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^ring[0-3]$", value):
            raise ValueError(r"must validate the regular expression /^ring[0-3]$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PXERollbackRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if target_version (nullable) is None
        # and model_fields_set contains the field
        if self.target_version is None and "target_version" in self.model_fields_set:
            _dict['target_version'] = None

        # set to None if profile (nullable) is None
        # and model_fields_set contains the field
        if self.profile is None and "profile" in self.model_fields_set:
            _dict['profile'] = None

        # set to None if ring (nullable) is None
        # and model_fields_set contains the field
        if self.ring is None and "ring" in self.model_fields_set:
            _dict['ring'] = None

        # set to None if site (nullable) is None
        # and model_fields_set contains the field
        if self.site is None and "site" in self.model_fields_set:
            _dict['site'] = None

        # set to None if device_mac (nullable) is None
        # and model_fields_set contains the field
        if self.device_mac is None and "device_mac" in self.model_fields_set:
            _dict['device_mac'] = None

        # set to None if backup_pxe_ip (nullable) is None
        # and model_fields_set contains the field
        if self.backup_pxe_ip is None and "backup_pxe_ip" in self.model_fields_set:
            _dict['backup_pxe_ip'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PXERollbackRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "pattern": obj.get("pattern"),
            "reason": obj.get("reason"),
            "target_version": obj.get("target_version"),
            "profile": obj.get("profile"),
            "ring": obj.get("ring"),
            "site": obj.get("site"),
            "device_mac": obj.get("device_mac"),
            "backup_pxe_ip": obj.get("backup_pxe_ip")
        })
        return _obj


