# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PXERollbackPattern(str, Enum):
    """
    Six rollback patterns defined in Issue 0041 § 4.7.
    """

    """
    allowed enum values
    """
    FULL = 'full'
    PROFILE = 'profile'
    RING = 'ring'
    SITE = 'site'
    SINGLE = 'single'
    ABORT = 'abort'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PXERollbackPattern from a JSON string"""
        return cls(json.loads(json_str))


