# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PXEBootEvent(str, Enum):
    """
    PXE boot lifecycle events recorded by agent-bootstrap.sh.
    """

    """
    allowed enum values
    """
    TOKEN_ISSUED = 'token_issued'
    BOOTSTRAP_COMPLETE = 'bootstrap_complete'
    BOOTSTRAP_FAILED = 'bootstrap_failed'
    FIRST_REGISTRATION = 'first_registration'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PXEBootEvent from a JSON string"""
        return cls(json.loads(json_str))


