#!/usr/bin/env python3
"""Output pytest coverage JSON to GitHub Step Summary.

Reads coverage.json (generated by pytest --cov-report=json) from the
current working directory and writes a Markdown table to GITHUB_STEP_SUMMARY.
Safe: reads only local files; no untrusted external inputs.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

GATE = 85


def main() -> int:
    # Allow override via env var so the script can run from the repo root
    # while coverage.json is generated in the working-directory of the job.
    env_path = os.environ.get("COVERAGE_JSON")
    p = Path(env_path) if env_path else Path("coverage.json")
    if not p.exists():
        print("coverage.json not found, skipping summary")
        return 0

    data = json.loads(p.read_text(encoding="utf-8"))
    totals = data.get("totals", {})
    pct = totals.get("percent_covered", 0.0)
    covered = totals.get("covered_lines", 0)
    total = totals.get("num_statements", 0)
    missing = totals.get("missing_lines", 0)

    gate_ok = pct >= GATE
    lines = [
        "## 📊 テストカバレッジ",
        "",
        "| 項目 | 値 |",
        "|---|---|",
        f"| 総ステートメント数 | {total} |",
        f"| カバー済み | {covered} |",
        f"| 未カバー | {missing} |",
        f"| **カバレッジ率** | **{pct:.1f}%** |",
        f"| ゲート閾値 | {GATE}% |",
        "",
        "✅ ゲート通過" if gate_ok else f"❌ ゲート失敗 — {pct:.1f}% < {GATE}%",
    ]
    text = "\n".join(lines) + "\n"

    summary = os.environ.get("GITHUB_STEP_SUMMARY", "")
    if summary:
        with open(summary, "a", encoding="utf-8") as fh:
            fh.write(text)
    else:
        sys.stdout.write(text)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
