/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryResponse
 */
export interface InventoryResponse {
    /**
     * 
     * @type {boolean}
     * @memberof InventoryResponse
     */
    accepted: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof InventoryResponse
     */
    duplicate: boolean;
    /**
     * 
     * @type {Date}
     * @memberof InventoryResponse
     */
    receivedAt: Date;
}

/**
 * Check if a given object implements the InventoryResponse interface.
 */
export function instanceOfInventoryResponse(value: object): value is InventoryResponse {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    if (!('duplicate' in value) || value['duplicate'] === undefined) return false;
    if (!('receivedAt' in value) || value['receivedAt'] === undefined) return false;
    return true;
}

export function InventoryResponseFromJSON(json: any): InventoryResponse {
    return InventoryResponseFromJSONTyped(json, false);
}

export function InventoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
        'duplicate': json['duplicate'],
        'receivedAt': (new Date(json['received_at'])),
    };
}

export function InventoryResponseToJSON(json: any): InventoryResponse {
    return InventoryResponseToJSONTyped(json, false);
}

export function InventoryResponseToJSONTyped(value?: InventoryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
        'duplicate': value['duplicate'],
        'received_at': value['receivedAt'].toISOString(),
    };
}

