/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IsoBuildJobResponse } from './IsoBuildJobResponse';
import {
    IsoBuildJobResponseFromJSON,
    IsoBuildJobResponseFromJSONTyped,
    IsoBuildJobResponseToJSON,
    IsoBuildJobResponseToJSONTyped,
} from './IsoBuildJobResponse';

/**
 * 
 * @export
 * @interface IsoBuildJobListResponse
 */
export interface IsoBuildJobListResponse {
    /**
     * 
     * @type {Array<IsoBuildJobResponse>}
     * @memberof IsoBuildJobListResponse
     */
    items: Array<IsoBuildJobResponse>;
    /**
     * 
     * @type {number}
     * @memberof IsoBuildJobListResponse
     */
    total: number;
}

/**
 * Check if a given object implements the IsoBuildJobListResponse interface.
 */
export function instanceOfIsoBuildJobListResponse(value: object): value is IsoBuildJobListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function IsoBuildJobListResponseFromJSON(json: any): IsoBuildJobListResponse {
    return IsoBuildJobListResponseFromJSONTyped(json, false);
}

export function IsoBuildJobListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsoBuildJobListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(IsoBuildJobResponseFromJSON)),
        'total': json['total'],
    };
}

export function IsoBuildJobListResponseToJSON(json: any): IsoBuildJobListResponse {
    return IsoBuildJobListResponseToJSONTyped(json, false);
}

export function IsoBuildJobListResponseToJSONTyped(value?: IsoBuildJobListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(IsoBuildJobResponseToJSON)),
        'total': value['total'],
    };
}

