/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsoBuildJobResponse
 */
export interface IsoBuildJobResponse {
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobResponse
     */
    id: string;
    /**
     * 
     * @type {IsoBuildJobResponseProfileEnum}
     * @memberof IsoBuildJobResponse
     */
    profile: IsoBuildJobResponseProfileEnum;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobResponse
     */
    requestedBy: string;
    /**
     * 
     * @type {IsoBuildJobResponseStatusEnum}
     * @memberof IsoBuildJobResponse
     */
    status: IsoBuildJobResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobResponse
     */
    gitRef: string;
    /**
     * 
     * @type {Date}
     * @memberof IsoBuildJobResponse
     */
    startedAt: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof IsoBuildJobResponse
     */
    finishedAt: Date | null;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobResponse
     */
    isoPath: string | null;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobResponse
     */
    isoSha256: string | null;
    /**
     * 
     * @type {number}
     * @memberof IsoBuildJobResponse
     */
    isoSizeBytes: number | null;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobResponse
     */
    logPath: string | null;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobResponse
     */
    errorMessage: string | null;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobResponse
     */
    notes: string | null;
    /**
     * 
     * @type {Date}
     * @memberof IsoBuildJobResponse
     */
    createdAt: Date;
}


/**
 * @export
 */
export const IsoBuildJobResponseProfileEnum = {
    Admin: 'admin',
    Standard: 'standard',
    Field: 'field',
    Kiosk: 'kiosk',
    AdminSupport: 'admin-support'
} as const;
export type IsoBuildJobResponseProfileEnum = typeof IsoBuildJobResponseProfileEnum[keyof typeof IsoBuildJobResponseProfileEnum];

/**
 * @export
 */
export const IsoBuildJobResponseStatusEnum = {
    Queued: 'queued',
    Running: 'running',
    Succeeded: 'succeeded',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type IsoBuildJobResponseStatusEnum = typeof IsoBuildJobResponseStatusEnum[keyof typeof IsoBuildJobResponseStatusEnum];


/**
 * Check if a given object implements the IsoBuildJobResponse interface.
 */
export function instanceOfIsoBuildJobResponse(value: object): value is IsoBuildJobResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('requestedBy' in value) || value['requestedBy'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('gitRef' in value) || value['gitRef'] === undefined) return false;
    if (!('startedAt' in value) || value['startedAt'] === undefined) return false;
    if (!('finishedAt' in value) || value['finishedAt'] === undefined) return false;
    if (!('isoPath' in value) || value['isoPath'] === undefined) return false;
    if (!('isoSha256' in value) || value['isoSha256'] === undefined) return false;
    if (!('isoSizeBytes' in value) || value['isoSizeBytes'] === undefined) return false;
    if (!('logPath' in value) || value['logPath'] === undefined) return false;
    if (!('errorMessage' in value) || value['errorMessage'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function IsoBuildJobResponseFromJSON(json: any): IsoBuildJobResponse {
    return IsoBuildJobResponseFromJSONTyped(json, false);
}

export function IsoBuildJobResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsoBuildJobResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'profile': json['profile'],
        'requestedBy': json['requested_by'],
        'status': json['status'],
        'gitRef': json['git_ref'],
        'startedAt': (json['started_at'] == null ? null : new Date(json['started_at'])),
        'finishedAt': (json['finished_at'] == null ? null : new Date(json['finished_at'])),
        'isoPath': json['iso_path'],
        'isoSha256': json['iso_sha256'],
        'isoSizeBytes': json['iso_size_bytes'],
        'logPath': json['log_path'],
        'errorMessage': json['error_message'],
        'notes': json['notes'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function IsoBuildJobResponseToJSON(json: any): IsoBuildJobResponse {
    return IsoBuildJobResponseToJSONTyped(json, false);
}

export function IsoBuildJobResponseToJSONTyped(value?: IsoBuildJobResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'profile': value['profile'],
        'requested_by': value['requestedBy'],
        'status': value['status'],
        'git_ref': value['gitRef'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'finished_at': value['finishedAt'] == null ? value['finishedAt'] : value['finishedAt'].toISOString(),
        'iso_path': value['isoPath'],
        'iso_sha256': value['isoSha256'],
        'iso_size_bytes': value['isoSizeBytes'],
        'log_path': value['logPath'],
        'error_message': value['errorMessage'],
        'notes': value['notes'],
        'created_at': value['createdAt'].toISOString(),
    };
}

