/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Liveness probe response — process-level vitals only.
 * 
 * Deliberately excludes storage/redis status: a downstream outage must not
 * trigger pod restart. Use ``/health/ready`` (or legacy ``/health``) for
 * deep dependency checks.
 * @export
 * @interface LivenessResponse
 */
export interface LivenessResponse {
    /**
     * 
     * @type {LivenessResponseStatusEnum}
     * @memberof LivenessResponse
     */
    status?: LivenessResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof LivenessResponse
     */
    service?: string;
    /**
     * 
     * @type {string}
     * @memberof LivenessResponse
     */
    version: string;
    /**
     * 
     * @type {number}
     * @memberof LivenessResponse
     */
    uptimeSeconds?: number;
}


/**
 * @export
 */
export const LivenessResponseStatusEnum = {
    Ok: 'ok'
} as const;
export type LivenessResponseStatusEnum = typeof LivenessResponseStatusEnum[keyof typeof LivenessResponseStatusEnum];


/**
 * Check if a given object implements the LivenessResponse interface.
 */
export function instanceOfLivenessResponse(value: object): value is LivenessResponse {
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function LivenessResponseFromJSON(json: any): LivenessResponse {
    return LivenessResponseFromJSONTyped(json, false);
}

export function LivenessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LivenessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'service': json['service'] == null ? undefined : json['service'],
        'version': json['version'],
        'uptimeSeconds': json['uptime_seconds'] == null ? undefined : json['uptime_seconds'],
    };
}

export function LivenessResponseToJSON(json: any): LivenessResponse {
    return LivenessResponseToJSONTyped(json, false);
}

export function LivenessResponseToJSONTyped(value?: LivenessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'service': value['service'],
        'version': value['version'],
        'uptime_seconds': value['uptimeSeconds'],
    };
}

