/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * PXE boot lifecycle events recorded by agent-bootstrap.sh.
 * @export
 */
export const PXEBootEvent = {
    TokenIssued: 'token_issued',
    BootstrapComplete: 'bootstrap_complete',
    BootstrapFailed: 'bootstrap_failed',
    FirstRegistration: 'first_registration'
} as const;
export type PXEBootEvent = typeof PXEBootEvent[keyof typeof PXEBootEvent];


export function instanceOfPXEBootEvent(value: any): boolean {
    for (const key in PXEBootEvent) {
        if (Object.prototype.hasOwnProperty.call(PXEBootEvent, key)) {
            if (PXEBootEvent[key as keyof typeof PXEBootEvent] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PXEBootEventFromJSON(json: any): PXEBootEvent {
    return PXEBootEventFromJSONTyped(json, false);
}

export function PXEBootEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): PXEBootEvent {
    return json as PXEBootEvent;
}

export function PXEBootEventToJSON(value?: PXEBootEvent | null): any {
    return value as any;
}

export function PXEBootEventToJSONTyped(value: any, ignoreDiscriminator: boolean): PXEBootEvent {
    return value as PXEBootEvent;
}

