/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PXEBootEvent } from './PXEBootEvent';
import {
    PXEBootEventFromJSON,
    PXEBootEventFromJSONTyped,
    PXEBootEventToJSON,
    PXEBootEventToJSONTyped,
} from './PXEBootEvent';

/**
 * Payload from agent-bootstrap.sh reporting a boot event.
 * @export
 * @interface PXEEventRequest
 */
export interface PXEEventRequest {
    /**
     * 
     * @type {PXEBootEvent}
     * @memberof PXEEventRequest
     */
    event: PXEBootEvent;
    /**
     * 
     * @type {string}
     * @memberof PXEEventRequest
     */
    profile: string;
    /**
     * 
     * @type {string}
     * @memberof PXEEventRequest
     */
    fingerprint: string;
    /**
     * 
     * @type {number}
     * @memberof PXEEventRequest
     */
    durationSeconds?: number | null;
    /**
     * 
     * @type {string}
     * @memberof PXEEventRequest
     */
    errorMessage?: string | null;
}



/**
 * Check if a given object implements the PXEEventRequest interface.
 */
export function instanceOfPXEEventRequest(value: object): value is PXEEventRequest {
    if (!('event' in value) || value['event'] === undefined) return false;
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('fingerprint' in value) || value['fingerprint'] === undefined) return false;
    return true;
}

export function PXEEventRequestFromJSON(json: any): PXEEventRequest {
    return PXEEventRequestFromJSONTyped(json, false);
}

export function PXEEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PXEEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'event': PXEBootEventFromJSON(json['event']),
        'profile': json['profile'],
        'fingerprint': json['fingerprint'],
        'durationSeconds': json['duration_seconds'] == null ? undefined : json['duration_seconds'],
        'errorMessage': json['error_message'] == null ? undefined : json['error_message'],
    };
}

export function PXEEventRequestToJSON(json: any): PXEEventRequest {
    return PXEEventRequestToJSONTyped(json, false);
}

export function PXEEventRequestToJSONTyped(value?: PXEEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event': PXEBootEventToJSON(value['event']),
        'profile': value['profile'],
        'fingerprint': value['fingerprint'],
        'duration_seconds': value['durationSeconds'],
        'error_message': value['errorMessage'],
    };
}

