/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PXERollbackPattern } from './PXERollbackPattern';
import {
    PXERollbackPatternFromJSON,
    PXERollbackPatternFromJSONTyped,
    PXERollbackPatternToJSON,
    PXERollbackPatternToJSONTyped,
} from './PXERollbackPattern';

/**
 * Rollback intent recorded + script command returned for operator execution.
 * @export
 * @interface PXERollbackResponse
 */
export interface PXERollbackResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PXERollbackResponse
     */
    recorded?: boolean;
    /**
     * 
     * @type {PXERollbackPattern}
     * @memberof PXERollbackResponse
     */
    pattern: PXERollbackPattern;
    /**
     * Request-ID for audit trail correlation.
     * @type {string}
     * @memberof PXERollbackResponse
     */
    auditId: string;
    /**
     * Script file to execute on the PXE server.
     * @type {string}
     * @memberof PXERollbackResponse
     */
    scriptName: string;
    /**
     * Exact command to run (with --dry-run for preview).
     * @type {string}
     * @memberof PXERollbackResponse
     */
    command: string;
}



/**
 * Check if a given object implements the PXERollbackResponse interface.
 */
export function instanceOfPXERollbackResponse(value: object): value is PXERollbackResponse {
    if (!('pattern' in value) || value['pattern'] === undefined) return false;
    if (!('auditId' in value) || value['auditId'] === undefined) return false;
    if (!('scriptName' in value) || value['scriptName'] === undefined) return false;
    if (!('command' in value) || value['command'] === undefined) return false;
    return true;
}

export function PXERollbackResponseFromJSON(json: any): PXERollbackResponse {
    return PXERollbackResponseFromJSONTyped(json, false);
}

export function PXERollbackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PXERollbackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'recorded': json['recorded'] == null ? undefined : json['recorded'],
        'pattern': PXERollbackPatternFromJSON(json['pattern']),
        'auditId': json['audit_id'],
        'scriptName': json['script_name'],
        'command': json['command'],
    };
}

export function PXERollbackResponseToJSON(json: any): PXERollbackResponse {
    return PXERollbackResponseToJSONTyped(json, false);
}

export function PXERollbackResponseToJSONTyped(value?: PXERollbackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recorded': value['recorded'],
        'pattern': PXERollbackPatternToJSON(value['pattern']),
        'audit_id': value['auditId'],
        'script_name': value['scriptName'],
        'command': value['command'],
    };
}

