# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.iso_builds_api import IsoBuildsApi


class TestIsoBuildsApi(unittest.TestCase):
    """IsoBuildsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IsoBuildsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_iso_build_job_api_v1_iso_builds_job_id_cancel_post(self) -> None:
        """Test case for cancel_iso_build_job_api_v1_iso_builds_job_id_cancel_post

        Cancel Iso Build Job
        """
        pass

    def test_create_iso_build_job_api_v1_iso_builds_post(self) -> None:
        """Test case for create_iso_build_job_api_v1_iso_builds_post

        Create Iso Build Job
        """
        pass

    def test_download_iso_redirect_api_v1_iso_builds_job_id_download_get(self) -> None:
        """Test case for download_iso_redirect_api_v1_iso_builds_job_id_download_get

        Download Iso Redirect
        """
        pass

    def test_get_iso_build_job_api_v1_iso_builds_job_id_get(self) -> None:
        """Test case for get_iso_build_job_api_v1_iso_builds_job_id_get

        Get Iso Build Job
        """
        pass

    def test_iso_builder_cancel_admin_iso_builder_job_id_cancel_post(self) -> None:
        """Test case for iso_builder_cancel_admin_iso_builder_job_id_cancel_post

        Iso Builder Cancel
        """
        pass

    def test_iso_builder_detail_admin_iso_builder_job_id_get(self) -> None:
        """Test case for iso_builder_detail_admin_iso_builder_job_id_get

        Iso Builder Detail
        """
        pass

    def test_iso_builder_list_admin_iso_builder_get(self) -> None:
        """Test case for iso_builder_list_admin_iso_builder_get

        Iso Builder List
        """
        pass

    def test_iso_builder_new_form_admin_iso_builder_new_get(self) -> None:
        """Test case for iso_builder_new_form_admin_iso_builder_new_get

        Iso Builder New Form
        """
        pass

    def test_iso_builder_submit_admin_iso_builder_post(self) -> None:
        """Test case for iso_builder_submit_admin_iso_builder_post

        Iso Builder Submit
        """
        pass

    def test_list_iso_build_jobs_api_v1_iso_builds_get(self) -> None:
        """Test case for list_iso_build_jobs_api_v1_iso_builds_get

        List Iso Build Jobs
        """
        pass

    def test_stream_iso_build_log_api_v1_iso_builds_job_id_log_get(self) -> None:
        """Test case for stream_iso_build_log_api_v1_iso_builds_job_id_log_get

        Stream Iso Build Log
        """
        pass


if __name__ == '__main__':
    unittest.main()
