# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.token_rotate_request import TokenRotateRequest

class TestTokenRotateRequest(unittest.TestCase):
    """TokenRotateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenRotateRequest:
        """Test TokenRotateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenRotateRequest`
        """
        model = TokenRotateRequest()
        if include_optional:
            return TokenRotateRequest(
                device_id = 'z'
            )
        else:
            return TokenRotateRequest(
                device_id = 'z',
        )
        """

    def testTokenRotateRequest(self):
        """Test TokenRotateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
