# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.iso_build_summary import IsoBuildSummary

class TestIsoBuildSummary(unittest.TestCase):
    """IsoBuildSummary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IsoBuildSummary:
        """Test IsoBuildSummary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsoBuildSummary`
        """
        model = IsoBuildSummary()
        if include_optional:
            return IsoBuildSummary(
                total = 56,
                running = 56,
                succeeded = 56,
                failed = 56,
                cancelled = 56
            )
        else:
            return IsoBuildSummary(
        )
        """

    def testIsoBuildSummary(self):
        """Test IsoBuildSummary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
