# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.iso_build_job_response import IsoBuildJobResponse

class TestIsoBuildJobResponse(unittest.TestCase):
    """IsoBuildJobResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IsoBuildJobResponse:
        """Test IsoBuildJobResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsoBuildJobResponse`
        """
        model = IsoBuildJobResponse()
        if include_optional:
            return IsoBuildJobResponse(
                id = '',
                profile = 'admin',
                requested_by = '',
                status = 'queued',
                git_ref = '',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                iso_path = '',
                iso_sha256 = '',
                iso_size_bytes = 56,
                log_path = '',
                error_message = '',
                notes = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return IsoBuildJobResponse(
                id = '',
                profile = 'admin',
                requested_by = '',
                status = 'queued',
                git_ref = '',
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                iso_path = '',
                iso_sha256 = '',
                iso_size_bytes = 56,
                log_path = '',
                error_message = '',
                notes = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testIsoBuildJobResponse(self):
        """Test IsoBuildJobResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
