# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.admin_api import AdminApi


class TestAdminApi(unittest.TestCase):
    """AdminApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AdminApi()

    def tearDown(self) -> None:
        pass

    def test_device_detail_admin_devices_device_id_get(self) -> None:
        """Test case for device_detail_admin_devices_device_id_get

        Device Detail
        """
        pass

    def test_device_list_admin_get(self) -> None:
        """Test case for device_list_admin_get

        Device List
        """
        pass

    def test_iso_builder_cancel_admin_iso_builder_job_id_cancel_post(self) -> None:
        """Test case for iso_builder_cancel_admin_iso_builder_job_id_cancel_post

        Iso Builder Cancel
        """
        pass

    def test_iso_builder_detail_admin_iso_builder_job_id_get(self) -> None:
        """Test case for iso_builder_detail_admin_iso_builder_job_id_get

        Iso Builder Detail
        """
        pass

    def test_iso_builder_list_admin_iso_builder_get(self) -> None:
        """Test case for iso_builder_list_admin_iso_builder_get

        Iso Builder List
        """
        pass

    def test_iso_builder_new_form_admin_iso_builder_new_get(self) -> None:
        """Test case for iso_builder_new_form_admin_iso_builder_new_get

        Iso Builder New Form
        """
        pass

    def test_iso_builder_submit_admin_iso_builder_post(self) -> None:
        """Test case for iso_builder_submit_admin_iso_builder_post

        Iso Builder Submit
        """
        pass

    def test_pxe_rollback_page_admin_pxe_rollback_get(self) -> None:
        """Test case for pxe_rollback_page_admin_pxe_rollback_get

        Pxe Rollback Page
        """
        pass


if __name__ == '__main__':
    unittest.main()
