# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.dashboard_response import DashboardResponse

class TestDashboardResponse(unittest.TestCase):
    """DashboardResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DashboardResponse:
        """Test DashboardResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DashboardResponse`
        """
        model = DashboardResponse()
        if include_optional:
            return DashboardResponse(
                devices = cdx_client.models.device_summary.DeviceSummary(
                    total = 56, 
                    online = 56, 
                    offline = 56, 
                    warning = 56, ),
                iso_builds = cdx_client.models.iso_build_summary.IsoBuildSummary(
                    total = 56, 
                    running = 56, 
                    succeeded = 56, 
                    failed = 56, 
                    cancelled = 56, ),
                server = cdx_client.models.server_summary.ServerSummary(
                    storage = 'ok', 
                    redis = 'disabled', 
                    uptime_seconds = 1.337, )
            )
        else:
            return DashboardResponse(
        )
        """

    def testDashboardResponse(self):
        """Test DashboardResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
