# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.pxe_event_response import PXEEventResponse

class TestPXEEventResponse(unittest.TestCase):
    """PXEEventResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PXEEventResponse:
        """Test PXEEventResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PXEEventResponse`
        """
        model = PXEEventResponse()
        if include_optional:
            return PXEEventResponse(
                recorded = True,
                event = 'token_issued'
            )
        else:
            return PXEEventResponse(
                event = 'token_issued',
        )
        """

    def testPXEEventResponse(self):
        """Test PXEEventResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
