# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.registration_token_request import RegistrationTokenRequest

class TestRegistrationTokenRequest(unittest.TestCase):
    """RegistrationTokenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegistrationTokenRequest:
        """Test RegistrationTokenRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegistrationTokenRequest`
        """
        model = RegistrationTokenRequest()
        if include_optional:
            return RegistrationTokenRequest(
                profile = 'standard',
                fingerprint = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263'
            )
        else:
            return RegistrationTokenRequest(
                profile = 'standard',
                fingerprint = 'bf325375e030fccba00917317c574773100bf03b5fc61486286e564b23e9566b0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263',
        )
        """

    def testRegistrationTokenRequest(self):
        """Test RegistrationTokenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
