# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.policy_response import PolicyResponse

class TestPolicyResponse(unittest.TestCase):
    """PolicyResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyResponse:
        """Test PolicyResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyResponse`
        """
        model = PolicyResponse()
        if include_optional:
            return PolicyResponse(
                profile = 'standard',
                update_ring = 'ring0',
                heartbeat_interval_seconds = 10.0,
                inventory_interval_seconds = 60.0,
                policy_version = 1.0
            )
        else:
            return PolicyResponse(
                profile = 'standard',
                update_ring = 'ring0',
                heartbeat_interval_seconds = 10.0,
                inventory_interval_seconds = 60.0,
                policy_version = 1.0,
        )
        """

    def testPolicyResponse(self):
        """Test PolicyResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
