# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.confirm_request import ConfirmRequest

class TestConfirmRequest(unittest.TestCase):
    """ConfirmRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfirmRequest:
        """Test ConfirmRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfirmRequest`
        """
        model = ConfirmRequest()
        if include_optional:
            return ConfirmRequest(
                serial_number = '',
                hostname = '',
                profile = 'standard',
                location = '',
                notes = ''
            )
        else:
            return ConfirmRequest(
                serial_number = '',
                hostname = '',
        )
        """

    def testConfirmRequest(self):
        """Test ConfirmRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
