# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.pxe_rollback_request import PXERollbackRequest

class TestPXERollbackRequest(unittest.TestCase):
    """PXERollbackRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PXERollbackRequest:
        """Test PXERollbackRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PXERollbackRequest`
        """
        model = PXERollbackRequest()
        if include_optional:
            return PXERollbackRequest(
                pattern = 'full',
                reason = '0123456789',
                target_version = '',
                profile = 'kiosk',
                ring = 'ring2',
                site = '',
                device_mac = '',
                backup_pxe_ip = ''
            )
        else:
            return PXERollbackRequest(
                pattern = 'full',
                reason = '0123456789',
        )
        """

    def testPXERollbackRequest(self):
        """Test PXERollbackRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
