# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.heartbeat_api import HeartbeatApi


class TestHeartbeatApi(unittest.TestCase):
    """HeartbeatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HeartbeatApi()

    def tearDown(self) -> None:
        pass

    def test_ingest_heartbeat_api_v1_heartbeat_post(self) -> None:
        """Test case for ingest_heartbeat_api_v1_heartbeat_post

        Ingest Heartbeat
        """
        pass


if __name__ == '__main__':
    unittest.main()
