# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.pxe_rollback_response import PXERollbackResponse

class TestPXERollbackResponse(unittest.TestCase):
    """PXERollbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PXERollbackResponse:
        """Test PXERollbackResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PXERollbackResponse`
        """
        model = PXERollbackResponse()
        if include_optional:
            return PXERollbackResponse(
                recorded = True,
                pattern = 'full',
                audit_id = '',
                script_name = '',
                command = ''
            )
        else:
            return PXERollbackResponse(
                pattern = 'full',
                audit_id = '',
                script_name = '',
                command = '',
        )
        """

    def testPXERollbackResponse(self):
        """Test PXERollbackResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
