# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.registration_api import RegistrationApi


class TestRegistrationApi(unittest.TestCase):
    """RegistrationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RegistrationApi()

    def tearDown(self) -> None:
        pass

    def test_create_registration_token_api_v1_devices_registration_tokens_post(self) -> None:
        """Test case for create_registration_token_api_v1_devices_registration_tokens_post

        Create Registration Token
        """
        pass

    def test_rotate_device_token_api_v1_auth_rotate_post(self) -> None:
        """Test case for rotate_device_token_api_v1_auth_rotate_post

        Rotate Device Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
