# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.pxe_boot_event import PXEBootEvent

class TestPXEBootEvent(unittest.TestCase):
    """PXEBootEvent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPXEBootEvent(self):
        """Test PXEBootEvent"""
        # inst = PXEBootEvent()

if __name__ == '__main__':
    unittest.main()
