# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.iso_build_job_create_request import IsoBuildJobCreateRequest

class TestIsoBuildJobCreateRequest(unittest.TestCase):
    """IsoBuildJobCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IsoBuildJobCreateRequest:
        """Test IsoBuildJobCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IsoBuildJobCreateRequest`
        """
        model = IsoBuildJobCreateRequest()
        if include_optional:
            return IsoBuildJobCreateRequest(
                profile = 'admin',
                git_ref = '0',
                notes = ''
            )
        else:
            return IsoBuildJobCreateRequest(
                profile = 'admin',
                git_ref = '0',
        )
        """

    def testIsoBuildJobCreateRequest(self):
        """Test IsoBuildJobCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
