# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.pxe_rollback_pattern import PXERollbackPattern

class TestPXERollbackPattern(unittest.TestCase):
    """PXERollbackPattern unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPXERollbackPattern(self):
        """Test PXERollbackPattern"""
        # inst = PXERollbackPattern()

if __name__ == '__main__':
    unittest.main()
