# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.policy_api import PolicyApi


class TestPolicyApi(unittest.TestCase):
    """PolicyApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PolicyApi()

    def tearDown(self) -> None:
        pass

    def test_get_policy_api_v1_policy_get(self) -> None:
        """Test case for get_policy_api_v1_policy_get

        Get Policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
