# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.inventory_api import InventoryApi


class TestInventoryApi(unittest.TestCase):
    """InventoryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InventoryApi()

    def tearDown(self) -> None:
        pass

    def test_ingest_inventory_api_v1_inventory_post(self) -> None:
        """Test case for ingest_inventory_api_v1_inventory_post

        Ingest Inventory
        """
        pass


if __name__ == '__main__':
    unittest.main()
