/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface DeviceDetailAdminDevicesDeviceIdGetRequest {
    deviceId: string;
}

export interface IsoBuilderCancelAdminIsoBuilderJobIdCancelPostRequest {
    jobId: string;
}

export interface IsoBuilderDetailAdminIsoBuilderJobIdGetRequest {
    jobId: string;
}

export interface IsoBuilderListAdminIsoBuilderGetRequest {
    profile?: string | null;
    statusFilter?: string | null;
}

export interface IsoBuilderSubmitAdminIsoBuilderPostRequest {
    profile: string;
    gitRef: string;
    notes?: string;
}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI {

    /**
     * Creates request options for deviceDetailAdminDevicesDeviceIdGet without sending the request
     */
    async deviceDetailAdminDevicesDeviceIdGetRequestOpts(requestParameters: DeviceDetailAdminDevicesDeviceIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['deviceId'] == null) {
            throw new runtime.RequiredError(
                'deviceId',
                'Required parameter "deviceId" was null or undefined when calling deviceDetailAdminDevicesDeviceIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/devices/{device_id}`;
        urlPath = urlPath.replace(`{${"device_id"}}`, encodeURIComponent(String(requestParameters['deviceId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Render the per-device detail page (heartbeats + inventory + policy).
     * Device Detail
     */
    async deviceDetailAdminDevicesDeviceIdGetRaw(requestParameters: DeviceDetailAdminDevicesDeviceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.deviceDetailAdminDevicesDeviceIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Render the per-device detail page (heartbeats + inventory + policy).
     * Device Detail
     */
    async deviceDetailAdminDevicesDeviceIdGet(requestParameters: DeviceDetailAdminDevicesDeviceIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.deviceDetailAdminDevicesDeviceIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deviceListAdminGet without sending the request
     */
    async deviceListAdminGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Render the device list page with online/offline status badges.
     * Device List
     */
    async deviceListAdminGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.deviceListAdminGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Render the device list page with online/offline status badges.
     * Device List
     */
    async deviceListAdminGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.deviceListAdminGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderCancelAdminIsoBuilderJobIdCancelPost without sending the request
     */
    async isoBuilderCancelAdminIsoBuilderJobIdCancelPostRequestOpts(requestParameters: IsoBuilderCancelAdminIsoBuilderJobIdCancelPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling isoBuilderCancelAdminIsoBuilderJobIdCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/iso-builder/{job_id}/cancel`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iso Builder Cancel
     */
    async isoBuilderCancelAdminIsoBuilderJobIdCancelPostRaw(requestParameters: IsoBuilderCancelAdminIsoBuilderJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.isoBuilderCancelAdminIsoBuilderJobIdCancelPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder Cancel
     */
    async isoBuilderCancelAdminIsoBuilderJobIdCancelPost(requestParameters: IsoBuilderCancelAdminIsoBuilderJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.isoBuilderCancelAdminIsoBuilderJobIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderDetailAdminIsoBuilderJobIdGet without sending the request
     */
    async isoBuilderDetailAdminIsoBuilderJobIdGetRequestOpts(requestParameters: IsoBuilderDetailAdminIsoBuilderJobIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling isoBuilderDetailAdminIsoBuilderJobIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/iso-builder/{job_id}`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iso Builder Detail
     */
    async isoBuilderDetailAdminIsoBuilderJobIdGetRaw(requestParameters: IsoBuilderDetailAdminIsoBuilderJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.isoBuilderDetailAdminIsoBuilderJobIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder Detail
     */
    async isoBuilderDetailAdminIsoBuilderJobIdGet(requestParameters: IsoBuilderDetailAdminIsoBuilderJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.isoBuilderDetailAdminIsoBuilderJobIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderListAdminIsoBuilderGet without sending the request
     */
    async isoBuilderListAdminIsoBuilderGetRequestOpts(requestParameters: IsoBuilderListAdminIsoBuilderGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['profile'] != null) {
            queryParameters['profile'] = requestParameters['profile'];
        }

        if (requestParameters['statusFilter'] != null) {
            queryParameters['status_filter'] = requestParameters['statusFilter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/iso-builder`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iso Builder List
     */
    async isoBuilderListAdminIsoBuilderGetRaw(requestParameters: IsoBuilderListAdminIsoBuilderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.isoBuilderListAdminIsoBuilderGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder List
     */
    async isoBuilderListAdminIsoBuilderGet(requestParameters: IsoBuilderListAdminIsoBuilderGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.isoBuilderListAdminIsoBuilderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderNewFormAdminIsoBuilderNewGet without sending the request
     */
    async isoBuilderNewFormAdminIsoBuilderNewGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/iso-builder/new`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iso Builder New Form
     */
    async isoBuilderNewFormAdminIsoBuilderNewGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.isoBuilderNewFormAdminIsoBuilderNewGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder New Form
     */
    async isoBuilderNewFormAdminIsoBuilderNewGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.isoBuilderNewFormAdminIsoBuilderNewGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderSubmitAdminIsoBuilderPost without sending the request
     */
    async isoBuilderSubmitAdminIsoBuilderPostRequestOpts(requestParameters: IsoBuilderSubmitAdminIsoBuilderPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['profile'] == null) {
            throw new runtime.RequiredError(
                'profile',
                'Required parameter "profile" was null or undefined when calling isoBuilderSubmitAdminIsoBuilderPost().'
            );
        }

        if (requestParameters['gitRef'] == null) {
            throw new runtime.RequiredError(
                'gitRef',
                'Required parameter "gitRef" was null or undefined when calling isoBuilderSubmitAdminIsoBuilderPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['profile'] != null) {
            formParams.append('profile', requestParameters['profile'] as any);
        }

        if (requestParameters['gitRef'] != null) {
            formParams.append('git_ref', requestParameters['gitRef'] as any);
        }

        if (requestParameters['notes'] != null) {
            formParams.append('notes', requestParameters['notes'] as any);
        }


        let urlPath = `/admin/iso-builder`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Iso Builder Submit
     */
    async isoBuilderSubmitAdminIsoBuilderPostRaw(requestParameters: IsoBuilderSubmitAdminIsoBuilderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.isoBuilderSubmitAdminIsoBuilderPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder Submit
     */
    async isoBuilderSubmitAdminIsoBuilderPost(requestParameters: IsoBuilderSubmitAdminIsoBuilderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.isoBuilderSubmitAdminIsoBuilderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for pxeRollbackPageAdminPxeRollbackGet without sending the request
     */
    async pxeRollbackPageAdminPxeRollbackGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/pxe-rollback`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Render the PXE rollback console (Issue 0042 Phase 4.5).
     * Pxe Rollback Page
     */
    async pxeRollbackPageAdminPxeRollbackGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.pxeRollbackPageAdminPxeRollbackGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Render the PXE rollback console (Issue 0042 Phase 4.5).
     * Pxe Rollback Page
     */
    async pxeRollbackPageAdminPxeRollbackGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.pxeRollbackPageAdminPxeRollbackGetRaw(initOverrides);
        return await response.value();
    }

}
