/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DashboardResponse,
} from '../models/index';
import {
    DashboardResponseFromJSON,
    DashboardResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DashboardApi extends runtime.BaseAPI {

    /**
     * Creates request options for dashboardApiV1DashboardGet without sending the request
     */
    async dashboardApiV1DashboardGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/dashboard`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Aggregate dashboard summary — devices + ISO builds + server health.
     * Dashboard
     */
    async dashboardApiV1DashboardGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DashboardResponse>> {
        const requestOptions = await this.dashboardApiV1DashboardGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DashboardResponseFromJSON(jsonValue));
    }

    /**
     * Aggregate dashboard summary — devices + ISO builds + server health.
     * Dashboard
     */
    async dashboardApiV1DashboardGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DashboardResponse> {
        const response = await this.dashboardApiV1DashboardGetRaw(initOverrides);
        return await response.value();
    }

}
