/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  RegisterRequest,
  RegisterResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    RegisterRequestFromJSON,
    RegisterRequestToJSON,
    RegisterResponseFromJSON,
    RegisterResponseToJSON,
} from '../models/index';

export interface RegisterDeviceApiV1DevicesRegisterPostRequest {
    registerRequest: RegisterRequest;
}

/**
 * 
 */
export class DevicesApi extends runtime.BaseAPI {

    /**
     * Creates request options for registerDeviceApiV1DevicesRegisterPost without sending the request
     */
    async registerDeviceApiV1DevicesRegisterPostRequestOpts(requestParameters: RegisterDeviceApiV1DevicesRegisterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registerRequest'] == null) {
            throw new runtime.RequiredError(
                'registerRequest',
                'Required parameter "registerRequest" was null or undefined when calling registerDeviceApiV1DevicesRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/devices/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegisterRequestToJSON(requestParameters['registerRequest']),
        };
    }

    /**
     * Register Device
     */
    async registerDeviceApiV1DevicesRegisterPostRaw(requestParameters: RegisterDeviceApiV1DevicesRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegisterResponse>> {
        const requestOptions = await this.registerDeviceApiV1DevicesRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegisterResponseFromJSON(jsonValue));
    }

    /**
     * Register Device
     */
    async registerDeviceApiV1DevicesRegisterPost(requestParameters: RegisterDeviceApiV1DevicesRegisterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegisterResponse> {
        const response = await this.registerDeviceApiV1DevicesRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
