/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthResponse,
  LivenessResponse,
} from '../models/index';
import {
    HealthResponseFromJSON,
    HealthResponseToJSON,
    LivenessResponseFromJSON,
    LivenessResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     * Creates request options for healthHealthGet without sending the request
     */
    async healthHealthGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Legacy combined health endpoint (kept stable; identical to /health/ready).
     * Health
     */
    async healthHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const requestOptions = await this.healthHealthGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Legacy combined health endpoint (kept stable; identical to /health/ready).
     * Health
     */
    async healthHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.healthHealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthLiveHealthLiveGet without sending the request
     */
    async healthLiveHealthLiveGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health/live`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Kubernetes-style liveness probe — process-level vitals only.
     * Health Live
     */
    async healthLiveHealthLiveGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LivenessResponse>> {
        const requestOptions = await this.healthLiveHealthLiveGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LivenessResponseFromJSON(jsonValue));
    }

    /**
     * Kubernetes-style liveness probe — process-level vitals only.
     * Health Live
     */
    async healthLiveHealthLiveGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LivenessResponse> {
        const response = await this.healthLiveHealthLiveGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for healthReadyHealthReadyGet without sending the request
     */
    async healthReadyHealthReadyGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health/ready`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Kubernetes-style readiness probe — fails 503 on dependency outage.
     * Health Ready
     */
    async healthReadyHealthReadyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const requestOptions = await this.healthReadyHealthReadyGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Kubernetes-style readiness probe — fails 503 on dependency outage.
     * Health Ready
     */
    async healthReadyHealthReadyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.healthReadyHealthReadyGetRaw(initOverrides);
        return await response.value();
    }

}
