/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HeartbeatResponse,
} from '../models/index';
import {
    HeartbeatResponseFromJSON,
    HeartbeatResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class HeartbeatApi extends runtime.BaseAPI {

    /**
     * Creates request options for ingestHeartbeatApiV1HeartbeatPost without sending the request
     */
    async ingestHeartbeatApiV1HeartbeatPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/heartbeat`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ingest Heartbeat
     */
    async ingestHeartbeatApiV1HeartbeatPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HeartbeatResponse>> {
        const requestOptions = await this.ingestHeartbeatApiV1HeartbeatPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HeartbeatResponseFromJSON(jsonValue));
    }

    /**
     * Ingest Heartbeat
     */
    async ingestHeartbeatApiV1HeartbeatPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HeartbeatResponse> {
        const response = await this.ingestHeartbeatApiV1HeartbeatPostRaw(initOverrides);
        return await response.value();
    }

}
