/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  InventoryResponse,
} from '../models/index';
import {
    InventoryResponseFromJSON,
    InventoryResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class InventoryApi extends runtime.BaseAPI {

    /**
     * Creates request options for ingestInventoryApiV1InventoryPost without sending the request
     */
    async ingestInventoryApiV1InventoryPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/inventory`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Ingest Inventory
     */
    async ingestInventoryApiV1InventoryPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<InventoryResponse>> {
        const requestOptions = await this.ingestInventoryApiV1InventoryPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InventoryResponseFromJSON(jsonValue));
    }

    /**
     * Ingest Inventory
     */
    async ingestInventoryApiV1InventoryPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<InventoryResponse> {
        const response = await this.ingestInventoryApiV1InventoryPostRaw(initOverrides);
        return await response.value();
    }

}
