/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  IsoBuildJobCreateRequest,
  IsoBuildJobListResponse,
  IsoBuildJobResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    IsoBuildJobCreateRequestFromJSON,
    IsoBuildJobCreateRequestToJSON,
    IsoBuildJobListResponseFromJSON,
    IsoBuildJobListResponseToJSON,
    IsoBuildJobResponseFromJSON,
    IsoBuildJobResponseToJSON,
} from '../models/index';

export interface CancelIsoBuildJobApiV1IsoBuildsJobIdCancelPostRequest {
    jobId: string;
}

export interface CreateIsoBuildJobApiV1IsoBuildsPostRequest {
    isoBuildJobCreateRequest: IsoBuildJobCreateRequest;
}

export interface DownloadIsoRedirectApiV1IsoBuildsJobIdDownloadGetRequest {
    jobId: string;
}

export interface GetIsoBuildJobApiV1IsoBuildsJobIdGetRequest {
    jobId: string;
}

export interface IsoBuilderCancelAdminIsoBuilderJobIdCancelPostRequest {
    jobId: string;
}

export interface IsoBuilderDetailAdminIsoBuilderJobIdGetRequest {
    jobId: string;
}

export interface IsoBuilderListAdminIsoBuilderGetRequest {
    profile?: string | null;
    statusFilter?: string | null;
}

export interface IsoBuilderSubmitAdminIsoBuilderPostRequest {
    profile: string;
    gitRef: string;
    notes?: string;
}

export interface ListIsoBuildJobsApiV1IsoBuildsGetRequest {
    profile?: ListIsoBuildJobsApiV1IsoBuildsGetProfileEnum;
    statusFilter?: ListIsoBuildJobsApiV1IsoBuildsGetStatusFilterEnum;
    limit?: number;
    offset?: number;
}

export interface StreamIsoBuildLogApiV1IsoBuildsJobIdLogGetRequest {
    jobId: string;
}

/**
 * 
 */
export class IsoBuildsApi extends runtime.BaseAPI {

    /**
     * Creates request options for cancelIsoBuildJobApiV1IsoBuildsJobIdCancelPost without sending the request
     */
    async cancelIsoBuildJobApiV1IsoBuildsJobIdCancelPostRequestOpts(requestParameters: CancelIsoBuildJobApiV1IsoBuildsJobIdCancelPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling cancelIsoBuildJobApiV1IsoBuildsJobIdCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/iso-builds/{job_id}/cancel`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel Iso Build Job
     */
    async cancelIsoBuildJobApiV1IsoBuildsJobIdCancelPostRaw(requestParameters: CancelIsoBuildJobApiV1IsoBuildsJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IsoBuildJobResponse>> {
        const requestOptions = await this.cancelIsoBuildJobApiV1IsoBuildsJobIdCancelPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IsoBuildJobResponseFromJSON(jsonValue));
    }

    /**
     * Cancel Iso Build Job
     */
    async cancelIsoBuildJobApiV1IsoBuildsJobIdCancelPost(requestParameters: CancelIsoBuildJobApiV1IsoBuildsJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IsoBuildJobResponse> {
        const response = await this.cancelIsoBuildJobApiV1IsoBuildsJobIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createIsoBuildJobApiV1IsoBuildsPost without sending the request
     */
    async createIsoBuildJobApiV1IsoBuildsPostRequestOpts(requestParameters: CreateIsoBuildJobApiV1IsoBuildsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['isoBuildJobCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'isoBuildJobCreateRequest',
                'Required parameter "isoBuildJobCreateRequest" was null or undefined when calling createIsoBuildJobApiV1IsoBuildsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/iso-builds`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IsoBuildJobCreateRequestToJSON(requestParameters['isoBuildJobCreateRequest']),
        };
    }

    /**
     * Create Iso Build Job
     */
    async createIsoBuildJobApiV1IsoBuildsPostRaw(requestParameters: CreateIsoBuildJobApiV1IsoBuildsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IsoBuildJobResponse>> {
        const requestOptions = await this.createIsoBuildJobApiV1IsoBuildsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IsoBuildJobResponseFromJSON(jsonValue));
    }

    /**
     * Create Iso Build Job
     */
    async createIsoBuildJobApiV1IsoBuildsPost(requestParameters: CreateIsoBuildJobApiV1IsoBuildsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IsoBuildJobResponse> {
        const response = await this.createIsoBuildJobApiV1IsoBuildsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadIsoRedirectApiV1IsoBuildsJobIdDownloadGet without sending the request
     */
    async downloadIsoRedirectApiV1IsoBuildsJobIdDownloadGetRequestOpts(requestParameters: DownloadIsoRedirectApiV1IsoBuildsJobIdDownloadGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling downloadIsoRedirectApiV1IsoBuildsJobIdDownloadGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/iso-builds/{job_id}/download`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Redirect to a presigned MinIO URL for downloading the ISO.  Returns 307 Temporary Redirect when MinIO is configured and the job has succeeded. Returns 409 Conflict for non-terminal jobs, 404 if the job is unknown, and 503 if MinIO is not configured.
     * Download Iso Redirect
     */
    async downloadIsoRedirectApiV1IsoBuildsJobIdDownloadGetRaw(requestParameters: DownloadIsoRedirectApiV1IsoBuildsJobIdDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.downloadIsoRedirectApiV1IsoBuildsJobIdDownloadGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Redirect to a presigned MinIO URL for downloading the ISO.  Returns 307 Temporary Redirect when MinIO is configured and the job has succeeded. Returns 409 Conflict for non-terminal jobs, 404 if the job is unknown, and 503 if MinIO is not configured.
     * Download Iso Redirect
     */
    async downloadIsoRedirectApiV1IsoBuildsJobIdDownloadGet(requestParameters: DownloadIsoRedirectApiV1IsoBuildsJobIdDownloadGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.downloadIsoRedirectApiV1IsoBuildsJobIdDownloadGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getIsoBuildJobApiV1IsoBuildsJobIdGet without sending the request
     */
    async getIsoBuildJobApiV1IsoBuildsJobIdGetRequestOpts(requestParameters: GetIsoBuildJobApiV1IsoBuildsJobIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getIsoBuildJobApiV1IsoBuildsJobIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/iso-builds/{job_id}`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Iso Build Job
     */
    async getIsoBuildJobApiV1IsoBuildsJobIdGetRaw(requestParameters: GetIsoBuildJobApiV1IsoBuildsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IsoBuildJobResponse>> {
        const requestOptions = await this.getIsoBuildJobApiV1IsoBuildsJobIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IsoBuildJobResponseFromJSON(jsonValue));
    }

    /**
     * Get Iso Build Job
     */
    async getIsoBuildJobApiV1IsoBuildsJobIdGet(requestParameters: GetIsoBuildJobApiV1IsoBuildsJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IsoBuildJobResponse> {
        const response = await this.getIsoBuildJobApiV1IsoBuildsJobIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderCancelAdminIsoBuilderJobIdCancelPost without sending the request
     */
    async isoBuilderCancelAdminIsoBuilderJobIdCancelPostRequestOpts(requestParameters: IsoBuilderCancelAdminIsoBuilderJobIdCancelPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling isoBuilderCancelAdminIsoBuilderJobIdCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/iso-builder/{job_id}/cancel`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iso Builder Cancel
     */
    async isoBuilderCancelAdminIsoBuilderJobIdCancelPostRaw(requestParameters: IsoBuilderCancelAdminIsoBuilderJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.isoBuilderCancelAdminIsoBuilderJobIdCancelPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder Cancel
     */
    async isoBuilderCancelAdminIsoBuilderJobIdCancelPost(requestParameters: IsoBuilderCancelAdminIsoBuilderJobIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.isoBuilderCancelAdminIsoBuilderJobIdCancelPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderDetailAdminIsoBuilderJobIdGet without sending the request
     */
    async isoBuilderDetailAdminIsoBuilderJobIdGetRequestOpts(requestParameters: IsoBuilderDetailAdminIsoBuilderJobIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling isoBuilderDetailAdminIsoBuilderJobIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/iso-builder/{job_id}`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iso Builder Detail
     */
    async isoBuilderDetailAdminIsoBuilderJobIdGetRaw(requestParameters: IsoBuilderDetailAdminIsoBuilderJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.isoBuilderDetailAdminIsoBuilderJobIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder Detail
     */
    async isoBuilderDetailAdminIsoBuilderJobIdGet(requestParameters: IsoBuilderDetailAdminIsoBuilderJobIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.isoBuilderDetailAdminIsoBuilderJobIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderListAdminIsoBuilderGet without sending the request
     */
    async isoBuilderListAdminIsoBuilderGetRequestOpts(requestParameters: IsoBuilderListAdminIsoBuilderGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['profile'] != null) {
            queryParameters['profile'] = requestParameters['profile'];
        }

        if (requestParameters['statusFilter'] != null) {
            queryParameters['status_filter'] = requestParameters['statusFilter'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/iso-builder`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iso Builder List
     */
    async isoBuilderListAdminIsoBuilderGetRaw(requestParameters: IsoBuilderListAdminIsoBuilderGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.isoBuilderListAdminIsoBuilderGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder List
     */
    async isoBuilderListAdminIsoBuilderGet(requestParameters: IsoBuilderListAdminIsoBuilderGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.isoBuilderListAdminIsoBuilderGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderNewFormAdminIsoBuilderNewGet without sending the request
     */
    async isoBuilderNewFormAdminIsoBuilderNewGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/admin/iso-builder/new`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Iso Builder New Form
     */
    async isoBuilderNewFormAdminIsoBuilderNewGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.isoBuilderNewFormAdminIsoBuilderNewGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder New Form
     */
    async isoBuilderNewFormAdminIsoBuilderNewGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.isoBuilderNewFormAdminIsoBuilderNewGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for isoBuilderSubmitAdminIsoBuilderPost without sending the request
     */
    async isoBuilderSubmitAdminIsoBuilderPostRequestOpts(requestParameters: IsoBuilderSubmitAdminIsoBuilderPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['profile'] == null) {
            throw new runtime.RequiredError(
                'profile',
                'Required parameter "profile" was null or undefined when calling isoBuilderSubmitAdminIsoBuilderPost().'
            );
        }

        if (requestParameters['gitRef'] == null) {
            throw new runtime.RequiredError(
                'gitRef',
                'Required parameter "gitRef" was null or undefined when calling isoBuilderSubmitAdminIsoBuilderPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const consumes: runtime.Consume[] = [
            { contentType: 'application/x-www-form-urlencoded' },
        ];
        // @ts-ignore: canConsumeForm may be unused
        const canConsumeForm = runtime.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): any };
        let useForm = false;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new URLSearchParams();
        }

        if (requestParameters['profile'] != null) {
            formParams.append('profile', requestParameters['profile'] as any);
        }

        if (requestParameters['gitRef'] != null) {
            formParams.append('git_ref', requestParameters['gitRef'] as any);
        }

        if (requestParameters['notes'] != null) {
            formParams.append('notes', requestParameters['notes'] as any);
        }


        let urlPath = `/admin/iso-builder`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: formParams,
        };
    }

    /**
     * Iso Builder Submit
     */
    async isoBuilderSubmitAdminIsoBuilderPostRaw(requestParameters: IsoBuilderSubmitAdminIsoBuilderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.isoBuilderSubmitAdminIsoBuilderPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Iso Builder Submit
     */
    async isoBuilderSubmitAdminIsoBuilderPost(requestParameters: IsoBuilderSubmitAdminIsoBuilderPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.isoBuilderSubmitAdminIsoBuilderPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listIsoBuildJobsApiV1IsoBuildsGet without sending the request
     */
    async listIsoBuildJobsApiV1IsoBuildsGetRequestOpts(requestParameters: ListIsoBuildJobsApiV1IsoBuildsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['profile'] != null) {
            queryParameters['profile'] = requestParameters['profile'];
        }

        if (requestParameters['statusFilter'] != null) {
            queryParameters['status_filter'] = requestParameters['statusFilter'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/iso-builds`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Iso Build Jobs
     */
    async listIsoBuildJobsApiV1IsoBuildsGetRaw(requestParameters: ListIsoBuildJobsApiV1IsoBuildsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<IsoBuildJobListResponse>> {
        const requestOptions = await this.listIsoBuildJobsApiV1IsoBuildsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => IsoBuildJobListResponseFromJSON(jsonValue));
    }

    /**
     * List Iso Build Jobs
     */
    async listIsoBuildJobsApiV1IsoBuildsGet(requestParameters: ListIsoBuildJobsApiV1IsoBuildsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<IsoBuildJobListResponse> {
        const response = await this.listIsoBuildJobsApiV1IsoBuildsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for streamIsoBuildLogApiV1IsoBuildsJobIdLogGet without sending the request
     */
    async streamIsoBuildLogApiV1IsoBuildsJobIdLogGetRequestOpts(requestParameters: StreamIsoBuildLogApiV1IsoBuildsJobIdLogGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling streamIsoBuildLogApiV1IsoBuildsJobIdLogGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/iso-builds/{job_id}/log`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Stream build log lines as Server-Sent Events.  Connect with ``EventSource(\'/api/v1/iso-builds/{id}/log\')`` from the browser. Events emitted: - ``log``    — a single build log line - ``status`` — current job status (queued/running/succeeded/failed/cancelled) - ``ping``   — heartbeat when no new log lines are available - ``done``   — terminal state reached; client should close the EventSource - ``error``  — job not found or other error - ``timeout``— stream exceeded CDX_SSE_TIMEOUT without completion
     * Stream Iso Build Log
     */
    async streamIsoBuildLogApiV1IsoBuildsJobIdLogGetRaw(requestParameters: StreamIsoBuildLogApiV1IsoBuildsJobIdLogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<any>> {
        const requestOptions = await this.streamIsoBuildLogApiV1IsoBuildsJobIdLogGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<any>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Stream build log lines as Server-Sent Events.  Connect with ``EventSource(\'/api/v1/iso-builds/{id}/log\')`` from the browser. Events emitted: - ``log``    — a single build log line - ``status`` — current job status (queued/running/succeeded/failed/cancelled) - ``ping``   — heartbeat when no new log lines are available - ``done``   — terminal state reached; client should close the EventSource - ``error``  — job not found or other error - ``timeout``— stream exceeded CDX_SSE_TIMEOUT without completion
     * Stream Iso Build Log
     */
    async streamIsoBuildLogApiV1IsoBuildsJobIdLogGet(requestParameters: StreamIsoBuildLogApiV1IsoBuildsJobIdLogGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<any> {
        const response = await this.streamIsoBuildLogApiV1IsoBuildsJobIdLogGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ListIsoBuildJobsApiV1IsoBuildsGetProfileEnum = {
    Admin: 'admin',
    Standard: 'standard',
    Field: 'field',
    Kiosk: 'kiosk',
    AdminSupport: 'admin-support'
} as const;
export type ListIsoBuildJobsApiV1IsoBuildsGetProfileEnum = typeof ListIsoBuildJobsApiV1IsoBuildsGetProfileEnum[keyof typeof ListIsoBuildJobsApiV1IsoBuildsGetProfileEnum];
/**
 * @export
 */
export const ListIsoBuildJobsApiV1IsoBuildsGetStatusFilterEnum = {
    Queued: 'queued',
    Running: 'running',
    Succeeded: 'succeeded',
    Failed: 'failed',
    Cancelled: 'cancelled'
} as const;
export type ListIsoBuildJobsApiV1IsoBuildsGetStatusFilterEnum = typeof ListIsoBuildJobsApiV1IsoBuildsGetStatusFilterEnum[keyof typeof ListIsoBuildJobsApiV1IsoBuildsGetStatusFilterEnum];
