/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  PolicyResponse,
} from '../models/index';
import {
    PolicyResponseFromJSON,
    PolicyResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class PolicyApi extends runtime.BaseAPI {

    /**
     * Creates request options for getPolicyApiV1PolicyGet without sending the request
     */
    async getPolicyApiV1PolicyGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/policy`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Policy
     */
    async getPolicyApiV1PolicyGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PolicyResponse>> {
        const requestOptions = await this.getPolicyApiV1PolicyGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PolicyResponseFromJSON(jsonValue));
    }

    /**
     * Get Policy
     */
    async getPolicyApiV1PolicyGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PolicyResponse> {
        const response = await this.getPolicyApiV1PolicyGetRaw(initOverrides);
        return await response.value();
    }

}
