/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  PXEEventRequest,
  PXEEventResponse,
  PXERollbackRequest,
  PXERollbackResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PXEEventRequestFromJSON,
    PXEEventRequestToJSON,
    PXEEventResponseFromJSON,
    PXEEventResponseToJSON,
    PXERollbackRequestFromJSON,
    PXERollbackRequestToJSON,
    PXERollbackResponseFromJSON,
    PXERollbackResponseToJSON,
} from '../models/index';

export interface RecordPxeEventApiV1PxeEventsPostRequest {
    pXEEventRequest: PXEEventRequest;
}

export interface RequestPxeRollbackApiV1PxeRollbackPostRequest {
    pXERollbackRequest: PXERollbackRequest;
}

/**
 * 
 */
export class PxeApi extends runtime.BaseAPI {

    /**
     * Creates request options for recordPxeEventApiV1PxeEventsPost without sending the request
     */
    async recordPxeEventApiV1PxeEventsPostRequestOpts(requestParameters: RecordPxeEventApiV1PxeEventsPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pXEEventRequest'] == null) {
            throw new runtime.RequiredError(
                'pXEEventRequest',
                'Required parameter "pXEEventRequest" was null or undefined when calling recordPxeEventApiV1PxeEventsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/pxe/events`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PXEEventRequestToJSON(requestParameters['pXEEventRequest']),
        };
    }

    /**
     * Record a PXE boot lifecycle event and update Prometheus metrics.  Called by agent-bootstrap.sh at bootstrap_complete and bootstrap_failed. The token_issued event is recorded automatically when the registration token endpoint issues a token.
     * Record Pxe Event
     */
    async recordPxeEventApiV1PxeEventsPostRaw(requestParameters: RecordPxeEventApiV1PxeEventsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PXEEventResponse>> {
        const requestOptions = await this.recordPxeEventApiV1PxeEventsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PXEEventResponseFromJSON(jsonValue));
    }

    /**
     * Record a PXE boot lifecycle event and update Prometheus metrics.  Called by agent-bootstrap.sh at bootstrap_complete and bootstrap_failed. The token_issued event is recorded automatically when the registration token endpoint issues a token.
     * Record Pxe Event
     */
    async recordPxeEventApiV1PxeEventsPost(requestParameters: RecordPxeEventApiV1PxeEventsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PXEEventResponse> {
        const response = await this.recordPxeEventApiV1PxeEventsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for requestPxeRollbackApiV1PxeRollbackPost without sending the request
     */
    async requestPxeRollbackApiV1PxeRollbackPostRequestOpts(requestParameters: RequestPxeRollbackApiV1PxeRollbackPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pXERollbackRequest'] == null) {
            throw new runtime.RequiredError(
                'pXERollbackRequest',
                'Required parameter "pXERollbackRequest" was null or undefined when calling requestPxeRollbackApiV1PxeRollbackPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/pxe/rollback`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PXERollbackRequestToJSON(requestParameters['pXERollbackRequest']),
        };
    }

    /**
     * Record a PXE rollback intent and return the script command to execute.  The operator must SSH to the PXE server and run the returned command. Dry-run preview: append --dry-run to the returned command.
     * Request Pxe Rollback
     */
    async requestPxeRollbackApiV1PxeRollbackPostRaw(requestParameters: RequestPxeRollbackApiV1PxeRollbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PXERollbackResponse>> {
        const requestOptions = await this.requestPxeRollbackApiV1PxeRollbackPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PXERollbackResponseFromJSON(jsonValue));
    }

    /**
     * Record a PXE rollback intent and return the script command to execute.  The operator must SSH to the PXE server and run the returned command. Dry-run preview: append --dry-run to the returned command.
     * Request Pxe Rollback
     */
    async requestPxeRollbackApiV1PxeRollbackPost(requestParameters: RequestPxeRollbackApiV1PxeRollbackPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PXERollbackResponse> {
        const response = await this.requestPxeRollbackApiV1PxeRollbackPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
