/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  RegistrationTokenRequest,
  RegistrationTokenResponse,
  TokenRotateRequest,
  TokenRotateResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    RegistrationTokenRequestFromJSON,
    RegistrationTokenRequestToJSON,
    RegistrationTokenResponseFromJSON,
    RegistrationTokenResponseToJSON,
    TokenRotateRequestFromJSON,
    TokenRotateRequestToJSON,
    TokenRotateResponseFromJSON,
    TokenRotateResponseToJSON,
} from '../models/index';

export interface CreateRegistrationTokenApiV1DevicesRegistrationTokensPostRequest {
    registrationTokenRequest: RegistrationTokenRequest;
}

export interface RotateDeviceTokenApiV1AuthRotatePostRequest {
    tokenRotateRequest: TokenRotateRequest;
}

/**
 * 
 */
export class RegistrationApi extends runtime.BaseAPI {

    /**
     * Creates request options for createRegistrationTokenApiV1DevicesRegistrationTokensPost without sending the request
     */
    async createRegistrationTokenApiV1DevicesRegistrationTokensPostRequestOpts(requestParameters: CreateRegistrationTokenApiV1DevicesRegistrationTokensPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['registrationTokenRequest'] == null) {
            throw new runtime.RequiredError(
                'registrationTokenRequest',
                'Required parameter "registrationTokenRequest" was null or undefined when calling createRegistrationTokenApiV1DevicesRegistrationTokensPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/devices/registration-tokens`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegistrationTokenRequestToJSON(requestParameters['registrationTokenRequest']),
        };
    }

    /**
     * Issue an ephemeral registration token to a bootstrapping device.  Called by ``agent-bootstrap.sh`` during PXE provisioning.  The token is single-use (consumed on first ``/api/v1/devices/register`` call) and expires after 24 hours.
     * Create Registration Token
     */
    async createRegistrationTokenApiV1DevicesRegistrationTokensPostRaw(requestParameters: CreateRegistrationTokenApiV1DevicesRegistrationTokensPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RegistrationTokenResponse>> {
        const requestOptions = await this.createRegistrationTokenApiV1DevicesRegistrationTokensPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RegistrationTokenResponseFromJSON(jsonValue));
    }

    /**
     * Issue an ephemeral registration token to a bootstrapping device.  Called by ``agent-bootstrap.sh`` during PXE provisioning.  The token is single-use (consumed on first ``/api/v1/devices/register`` call) and expires after 24 hours.
     * Create Registration Token
     */
    async createRegistrationTokenApiV1DevicesRegistrationTokensPost(requestParameters: CreateRegistrationTokenApiV1DevicesRegistrationTokensPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RegistrationTokenResponse> {
        const response = await this.createRegistrationTokenApiV1DevicesRegistrationTokensPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rotateDeviceTokenApiV1AuthRotatePost without sending the request
     */
    async rotateDeviceTokenApiV1AuthRotatePostRequestOpts(requestParameters: RotateDeviceTokenApiV1AuthRotatePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tokenRotateRequest'] == null) {
            throw new runtime.RequiredError(
                'tokenRotateRequest',
                'Required parameter "tokenRotateRequest" was null or undefined when calling rotateDeviceTokenApiV1AuthRotatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/rotate`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TokenRotateRequestToJSON(requestParameters['tokenRotateRequest']),
        };
    }

    /**
     * Rotate a device\'s long-lived auth token (48-hour TTL).  Gated by HMAC-SHA256 device signature (same scheme as heartbeat/inventory). The agent calls this endpoint automatically before token expiry.
     * Rotate Device Token
     */
    async rotateDeviceTokenApiV1AuthRotatePostRaw(requestParameters: RotateDeviceTokenApiV1AuthRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TokenRotateResponse>> {
        const requestOptions = await this.rotateDeviceTokenApiV1AuthRotatePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TokenRotateResponseFromJSON(jsonValue));
    }

    /**
     * Rotate a device\'s long-lived auth token (48-hour TTL).  Gated by HMAC-SHA256 device signature (same scheme as heartbeat/inventory). The agent calls this endpoint automatically before token expiry.
     * Rotate Device Token
     */
    async rotateDeviceTokenApiV1AuthRotatePost(requestParameters: RotateDeviceTokenApiV1AuthRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TokenRotateResponse> {
        const response = await this.rotateDeviceTokenApiV1AuthRotatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
