/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ConfirmRequest,
  HTTPValidationError,
} from '../models/index';
import {
    ConfirmRequestFromJSON,
    ConfirmRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface ConfirmItemApiV1SerialConfirmItemIdPostRequest {
    itemId: string;
    confirmRequest: ConfirmRequest;
}

export interface DiscardItemApiV1SerialQueueItemIdDeleteRequest {
    itemId: string;
}

/**
 * 
 */
export class SerialScanApi extends runtime.BaseAPI {

    /**
     * Creates request options for confirmItemApiV1SerialConfirmItemIdPost without sending the request
     */
    async confirmItemApiV1SerialConfirmItemIdPostRequestOpts(requestParameters: ConfirmItemApiV1SerialConfirmItemIdPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling confirmItemApiV1SerialConfirmItemIdPost().'
            );
        }

        if (requestParameters['confirmRequest'] == null) {
            throw new runtime.RequiredError(
                'confirmRequest',
                'Required parameter "confirmRequest" was null or undefined when calling confirmItemApiV1SerialConfirmItemIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/serial/confirm/{item_id}`;
        urlPath = urlPath.replace(`{${"item_id"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ConfirmRequestToJSON(requestParameters['confirmRequest']),
        };
    }

    /**
     * Confirm OCR result and register serial + hostname in the deploy register.
     * Confirm Item
     */
    async confirmItemApiV1SerialConfirmItemIdPostRaw(requestParameters: ConfirmItemApiV1SerialConfirmItemIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.confirmItemApiV1SerialConfirmItemIdPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Confirm OCR result and register serial + hostname in the deploy register.
     * Confirm Item
     */
    async confirmItemApiV1SerialConfirmItemIdPost(requestParameters: ConfirmItemApiV1SerialConfirmItemIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.confirmItemApiV1SerialConfirmItemIdPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for discardItemApiV1SerialQueueItemIdDelete without sending the request
     */
    async discardItemApiV1SerialQueueItemIdDeleteRequestOpts(requestParameters: DiscardItemApiV1SerialQueueItemIdDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling discardItemApiV1SerialQueueItemIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/serial/queue/{item_id}`;
        urlPath = urlPath.replace(`{${"item_id"}}`, encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Remove an item from the queue (e.g. duplicate or unreadable scan).
     * Discard Item
     */
    async discardItemApiV1SerialQueueItemIdDeleteRaw(requestParameters: DiscardItemApiV1SerialQueueItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string | null; }>> {
        const requestOptions = await this.discardItemApiV1SerialQueueItemIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Remove an item from the queue (e.g. duplicate or unreadable scan).
     * Discard Item
     */
    async discardItemApiV1SerialQueueItemIdDelete(requestParameters: DiscardItemApiV1SerialQueueItemIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string | null; }> {
        const response = await this.discardItemApiV1SerialQueueItemIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getQueueApiV1SerialQueueGet without sending the request
     */
    async getQueueApiV1SerialQueueGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/serial/queue`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return OCR queue (pending + recently confirmed items).
     * Get Queue
     */
    async getQueueApiV1SerialQueueGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.getQueueApiV1SerialQueueGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Return OCR queue (pending + recently confirmed items).
     * Get Queue
     */
    async getQueueApiV1SerialQueueGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.getQueueApiV1SerialQueueGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for serialStatusApiV1SerialStatusGet without sending the request
     */
    async serialStatusApiV1SerialStatusGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/serial/status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Return file server mount status and pending image count.
     * Serial Status
     */
    async serialStatusApiV1SerialStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.serialStatusApiV1SerialStatusGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Return file server mount status and pending image count.
     * Serial Status
     */
    async serialStatusApiV1SerialStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.serialStatusApiV1SerialStatusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for triggerScanApiV1SerialScanPost without sending the request
     */
    async triggerScanApiV1SerialScanPostRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }

        let urlPath = `/api/v1/serial/scan`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Process all pending images in SERIAL_SCAN_PATH via easyocr.
     * Trigger Scan
     */
    async triggerScanApiV1SerialScanPostRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        const requestOptions = await this.triggerScanApiV1SerialScanPostRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Process all pending images in SERIAL_SCAN_PATH via easyocr.
     * Trigger Scan
     */
    async triggerScanApiV1SerialScanPost(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.triggerScanApiV1SerialScanPostRaw(initOverrides);
        return await response.value();
    }

}
