export * from './create-environmental-aspect.dto';
export * from './update-environmental-aspect.dto';
export * from './create-legal-requirement.dto';
export * from './update-legal-requirement.dto';
export * from './create-waste-record.dto';
export * from './update-waste-record.dto';
export * from './environmental-aspect-query.dto';
export * from './legal-requirement-query.dto';
export * from './waste-record-query.dto';
