# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cdx_client.models.pxe_rollback_pattern import PXERollbackPattern
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PXERollbackResponse(BaseModel):
    """
    Rollback intent recorded + script command returned for operator execution.
    """ # noqa: E501
    recorded: Optional[StrictBool] = True
    pattern: PXERollbackPattern
    audit_id: StrictStr = Field(description="Request-ID for audit trail correlation.")
    script_name: StrictStr = Field(description="Script file to execute on the PXE server.")
    command: StrictStr = Field(description="Exact command to run (with --dry-run for preview).")
    __properties: ClassVar[List[str]] = ["recorded", "pattern", "audit_id", "script_name", "command"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PXERollbackResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PXERollbackResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "recorded": obj.get("recorded") if obj.get("recorded") is not None else True,
            "pattern": obj.get("pattern"),
            "audit_id": obj.get("audit_id"),
            "script_name": obj.get("script_name"),
            "command": obj.get("command")
        })
        return _obj


