/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmRequest
 */
export interface ConfirmRequest {
    /**
     * 
     * @type {string}
     * @memberof ConfirmRequest
     */
    serialNumber: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmRequest
     */
    hostname: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmRequest
     */
    profile?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmRequest
     */
    location?: string;
    /**
     * 
     * @type {string}
     * @memberof ConfirmRequest
     */
    notes?: string;
}

/**
 * Check if a given object implements the ConfirmRequest interface.
 */
export function instanceOfConfirmRequest(value: object): value is ConfirmRequest {
    if (!('serialNumber' in value) || value['serialNumber'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    return true;
}

export function ConfirmRequestFromJSON(json: any): ConfirmRequest {
    return ConfirmRequestFromJSONTyped(json, false);
}

export function ConfirmRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'serialNumber': json['serial_number'],
        'hostname': json['hostname'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'location': json['location'] == null ? undefined : json['location'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ConfirmRequestToJSON(json: any): ConfirmRequest {
    return ConfirmRequestToJSONTyped(json, false);
}

export function ConfirmRequestToJSONTyped(value?: ConfirmRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'serial_number': value['serialNumber'],
        'hostname': value['hostname'],
        'profile': value['profile'],
        'location': value['location'],
        'notes': value['notes'],
    };
}

