/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IsoBuildSummary } from './IsoBuildSummary';
import {
    IsoBuildSummaryFromJSON,
    IsoBuildSummaryFromJSONTyped,
    IsoBuildSummaryToJSON,
    IsoBuildSummaryToJSONTyped,
} from './IsoBuildSummary';
import type { DeviceSummary } from './DeviceSummary';
import {
    DeviceSummaryFromJSON,
    DeviceSummaryFromJSONTyped,
    DeviceSummaryToJSON,
    DeviceSummaryToJSONTyped,
} from './DeviceSummary';
import type { ServerSummary } from './ServerSummary';
import {
    ServerSummaryFromJSON,
    ServerSummaryFromJSONTyped,
    ServerSummaryToJSON,
    ServerSummaryToJSONTyped,
} from './ServerSummary';

/**
 * 
 * @export
 * @interface DashboardResponse
 */
export interface DashboardResponse {
    /**
     * 
     * @type {DeviceSummary}
     * @memberof DashboardResponse
     */
    devices?: DeviceSummary;
    /**
     * 
     * @type {IsoBuildSummary}
     * @memberof DashboardResponse
     */
    isoBuilds?: IsoBuildSummary;
    /**
     * 
     * @type {ServerSummary}
     * @memberof DashboardResponse
     */
    server?: ServerSummary;
}

/**
 * Check if a given object implements the DashboardResponse interface.
 */
export function instanceOfDashboardResponse(value: object): value is DashboardResponse {
    return true;
}

export function DashboardResponseFromJSON(json: any): DashboardResponse {
    return DashboardResponseFromJSONTyped(json, false);
}

export function DashboardResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DashboardResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'devices': json['devices'] == null ? undefined : DeviceSummaryFromJSON(json['devices']),
        'isoBuilds': json['iso_builds'] == null ? undefined : IsoBuildSummaryFromJSON(json['iso_builds']),
        'server': json['server'] == null ? undefined : ServerSummaryFromJSON(json['server']),
    };
}

export function DashboardResponseToJSON(json: any): DashboardResponse {
    return DashboardResponseToJSONTyped(json, false);
}

export function DashboardResponseToJSONTyped(value?: DashboardResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'devices': DeviceSummaryToJSON(value['devices']),
        'iso_builds': IsoBuildSummaryToJSON(value['isoBuilds']),
        'server': ServerSummaryToJSON(value['server']),
    };
}

