/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeviceSummary
 */
export interface DeviceSummary {
    /**
     * 
     * @type {number}
     * @memberof DeviceSummary
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceSummary
     */
    online?: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceSummary
     */
    offline?: number;
    /**
     * 
     * @type {number}
     * @memberof DeviceSummary
     */
    warning?: number;
}

/**
 * Check if a given object implements the DeviceSummary interface.
 */
export function instanceOfDeviceSummary(value: object): value is DeviceSummary {
    return true;
}

export function DeviceSummaryFromJSON(json: any): DeviceSummary {
    return DeviceSummaryFromJSONTyped(json, false);
}

export function DeviceSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeviceSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'online': json['online'] == null ? undefined : json['online'],
        'offline': json['offline'] == null ? undefined : json['offline'],
        'warning': json['warning'] == null ? undefined : json['warning'],
    };
}

export function DeviceSummaryToJSON(json: any): DeviceSummary {
    return DeviceSummaryToJSONTyped(json, false);
}

export function DeviceSummaryToJSONTyped(value?: DeviceSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'online': value['online'],
        'offline': value['offline'],
        'warning': value['warning'],
    };
}

