/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthResponse
 */
export interface HealthResponse {
    /**
     * 
     * @type {HealthResponseStatusEnum}
     * @memberof HealthResponse
     */
    status?: HealthResponseStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    service?: string;
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    version: string;
    /**
     * 
     * @type {HealthResponseStorageEnum}
     * @memberof HealthResponse
     */
    storage?: HealthResponseStorageEnum;
    /**
     * 
     * @type {string}
     * @memberof HealthResponse
     */
    storageBackend?: string;
    /**
     * 
     * @type {HealthResponseRedisEnum}
     * @memberof HealthResponse
     */
    redis?: HealthResponseRedisEnum;
    /**
     * 
     * @type {number}
     * @memberof HealthResponse
     */
    uptimeSeconds?: number;
}


/**
 * @export
 */
export const HealthResponseStatusEnum = {
    Ok: 'ok',
    Degraded: 'degraded'
} as const;
export type HealthResponseStatusEnum = typeof HealthResponseStatusEnum[keyof typeof HealthResponseStatusEnum];

/**
 * @export
 */
export const HealthResponseStorageEnum = {
    Ok: 'ok',
    Error: 'error'
} as const;
export type HealthResponseStorageEnum = typeof HealthResponseStorageEnum[keyof typeof HealthResponseStorageEnum];

/**
 * @export
 */
export const HealthResponseRedisEnum = {
    Ok: 'ok',
    Error: 'error',
    Disabled: 'disabled'
} as const;
export type HealthResponseRedisEnum = typeof HealthResponseRedisEnum[keyof typeof HealthResponseRedisEnum];


/**
 * Check if a given object implements the HealthResponse interface.
 */
export function instanceOfHealthResponse(value: object): value is HealthResponse {
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function HealthResponseFromJSON(json: any): HealthResponse {
    return HealthResponseFromJSONTyped(json, false);
}

export function HealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'service': json['service'] == null ? undefined : json['service'],
        'version': json['version'],
        'storage': json['storage'] == null ? undefined : json['storage'],
        'storageBackend': json['storage_backend'] == null ? undefined : json['storage_backend'],
        'redis': json['redis'] == null ? undefined : json['redis'],
        'uptimeSeconds': json['uptime_seconds'] == null ? undefined : json['uptime_seconds'],
    };
}

export function HealthResponseToJSON(json: any): HealthResponse {
    return HealthResponseToJSONTyped(json, false);
}

export function HealthResponseToJSONTyped(value?: HealthResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'service': value['service'],
        'version': value['version'],
        'storage': value['storage'],
        'storage_backend': value['storageBackend'],
        'redis': value['redis'],
        'uptime_seconds': value['uptimeSeconds'],
    };
}

