/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HeartbeatResponse
 */
export interface HeartbeatResponse {
    /**
     * 
     * @type {boolean}
     * @memberof HeartbeatResponse
     */
    accepted: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof HeartbeatResponse
     */
    duplicate: boolean;
    /**
     * 
     * @type {Date}
     * @memberof HeartbeatResponse
     */
    receivedAt: Date;
}

/**
 * Check if a given object implements the HeartbeatResponse interface.
 */
export function instanceOfHeartbeatResponse(value: object): value is HeartbeatResponse {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    if (!('duplicate' in value) || value['duplicate'] === undefined) return false;
    if (!('receivedAt' in value) || value['receivedAt'] === undefined) return false;
    return true;
}

export function HeartbeatResponseFromJSON(json: any): HeartbeatResponse {
    return HeartbeatResponseFromJSONTyped(json, false);
}

export function HeartbeatResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HeartbeatResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
        'duplicate': json['duplicate'],
        'receivedAt': (new Date(json['received_at'])),
    };
}

export function HeartbeatResponseToJSON(json: any): HeartbeatResponse {
    return HeartbeatResponseToJSONTyped(json, false);
}

export function HeartbeatResponseToJSONTyped(value?: HeartbeatResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
        'duplicate': value['duplicate'],
        'received_at': value['receivedAt'].toISOString(),
    };
}

