/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IsoBuildSummary
 */
export interface IsoBuildSummary {
    /**
     * 
     * @type {number}
     * @memberof IsoBuildSummary
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof IsoBuildSummary
     */
    running?: number;
    /**
     * 
     * @type {number}
     * @memberof IsoBuildSummary
     */
    succeeded?: number;
    /**
     * 
     * @type {number}
     * @memberof IsoBuildSummary
     */
    failed?: number;
    /**
     * 
     * @type {number}
     * @memberof IsoBuildSummary
     */
    cancelled?: number;
}

/**
 * Check if a given object implements the IsoBuildSummary interface.
 */
export function instanceOfIsoBuildSummary(value: object): value is IsoBuildSummary {
    return true;
}

export function IsoBuildSummaryFromJSON(json: any): IsoBuildSummary {
    return IsoBuildSummaryFromJSONTyped(json, false);
}

export function IsoBuildSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsoBuildSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'total': json['total'] == null ? undefined : json['total'],
        'running': json['running'] == null ? undefined : json['running'],
        'succeeded': json['succeeded'] == null ? undefined : json['succeeded'],
        'failed': json['failed'] == null ? undefined : json['failed'],
        'cancelled': json['cancelled'] == null ? undefined : json['cancelled'],
    };
}

export function IsoBuildSummaryToJSON(json: any): IsoBuildSummary {
    return IsoBuildSummaryToJSONTyped(json, false);
}

export function IsoBuildSummaryToJSONTyped(value?: IsoBuildSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total': value['total'],
        'running': value['running'],
        'succeeded': value['succeeded'],
        'failed': value['failed'],
        'cancelled': value['cancelled'],
    };
}

