/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Operator-supplied parameters for enqueuing a new ISO build.
 * @export
 * @interface IsoBuildJobCreateRequest
 */
export interface IsoBuildJobCreateRequest {
    /**
     * 
     * @type {IsoBuildJobCreateRequestProfileEnum}
     * @memberof IsoBuildJobCreateRequest
     */
    profile: IsoBuildJobCreateRequestProfileEnum;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobCreateRequest
     */
    gitRef: string;
    /**
     * 
     * @type {string}
     * @memberof IsoBuildJobCreateRequest
     */
    notes?: string | null;
}


/**
 * @export
 */
export const IsoBuildJobCreateRequestProfileEnum = {
    Admin: 'admin',
    Standard: 'standard',
    Field: 'field',
    Kiosk: 'kiosk',
    AdminSupport: 'admin-support'
} as const;
export type IsoBuildJobCreateRequestProfileEnum = typeof IsoBuildJobCreateRequestProfileEnum[keyof typeof IsoBuildJobCreateRequestProfileEnum];


/**
 * Check if a given object implements the IsoBuildJobCreateRequest interface.
 */
export function instanceOfIsoBuildJobCreateRequest(value: object): value is IsoBuildJobCreateRequest {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('gitRef' in value) || value['gitRef'] === undefined) return false;
    return true;
}

export function IsoBuildJobCreateRequestFromJSON(json: any): IsoBuildJobCreateRequest {
    return IsoBuildJobCreateRequestFromJSONTyped(json, false);
}

export function IsoBuildJobCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IsoBuildJobCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': json['profile'],
        'gitRef': json['git_ref'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function IsoBuildJobCreateRequestToJSON(json: any): IsoBuildJobCreateRequest {
    return IsoBuildJobCreateRequestToJSONTyped(json, false);
}

export function IsoBuildJobCreateRequestToJSONTyped(value?: IsoBuildJobCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': value['profile'],
        'git_ref': value['gitRef'],
        'notes': value['notes'],
    };
}

