/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PolicyResponse
 */
export interface PolicyResponse {
    /**
     * 
     * @type {PolicyResponseProfileEnum}
     * @memberof PolicyResponse
     */
    profile: PolicyResponseProfileEnum;
    /**
     * 
     * @type {PolicyResponseUpdateRingEnum}
     * @memberof PolicyResponse
     */
    updateRing: PolicyResponseUpdateRingEnum;
    /**
     * 
     * @type {number}
     * @memberof PolicyResponse
     */
    heartbeatIntervalSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof PolicyResponse
     */
    inventoryIntervalSeconds: number;
    /**
     * 
     * @type {number}
     * @memberof PolicyResponse
     */
    policyVersion: number;
}


/**
 * @export
 */
export const PolicyResponseProfileEnum = {
    Standard: 'standard',
    Field: 'field',
    Kiosk: 'kiosk'
} as const;
export type PolicyResponseProfileEnum = typeof PolicyResponseProfileEnum[keyof typeof PolicyResponseProfileEnum];

/**
 * @export
 */
export const PolicyResponseUpdateRingEnum = {
    Ring0: 'ring0',
    Ring1: 'ring1',
    Ring2: 'ring2',
    Ring3: 'ring3'
} as const;
export type PolicyResponseUpdateRingEnum = typeof PolicyResponseUpdateRingEnum[keyof typeof PolicyResponseUpdateRingEnum];


/**
 * Check if a given object implements the PolicyResponse interface.
 */
export function instanceOfPolicyResponse(value: object): value is PolicyResponse {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('updateRing' in value) || value['updateRing'] === undefined) return false;
    if (!('heartbeatIntervalSeconds' in value) || value['heartbeatIntervalSeconds'] === undefined) return false;
    if (!('inventoryIntervalSeconds' in value) || value['inventoryIntervalSeconds'] === undefined) return false;
    if (!('policyVersion' in value) || value['policyVersion'] === undefined) return false;
    return true;
}

export function PolicyResponseFromJSON(json: any): PolicyResponse {
    return PolicyResponseFromJSONTyped(json, false);
}

export function PolicyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PolicyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': json['profile'],
        'updateRing': json['update_ring'],
        'heartbeatIntervalSeconds': json['heartbeat_interval_seconds'],
        'inventoryIntervalSeconds': json['inventory_interval_seconds'],
        'policyVersion': json['policy_version'],
    };
}

export function PolicyResponseToJSON(json: any): PolicyResponse {
    return PolicyResponseToJSONTyped(json, false);
}

export function PolicyResponseToJSONTyped(value?: PolicyResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': value['profile'],
        'update_ring': value['updateRing'],
        'heartbeat_interval_seconds': value['heartbeatIntervalSeconds'],
        'inventory_interval_seconds': value['inventoryIntervalSeconds'],
        'policy_version': value['policyVersion'],
    };
}

