/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PXEBootEvent } from './PXEBootEvent';
import {
    PXEBootEventFromJSON,
    PXEBootEventFromJSONTyped,
    PXEBootEventToJSON,
    PXEBootEventToJSONTyped,
} from './PXEBootEvent';

/**
 * Acknowledgement returned to agent-bootstrap.sh.
 * @export
 * @interface PXEEventResponse
 */
export interface PXEEventResponse {
    /**
     * 
     * @type {boolean}
     * @memberof PXEEventResponse
     */
    recorded?: boolean;
    /**
     * 
     * @type {PXEBootEvent}
     * @memberof PXEEventResponse
     */
    event: PXEBootEvent;
}



/**
 * Check if a given object implements the PXEEventResponse interface.
 */
export function instanceOfPXEEventResponse(value: object): value is PXEEventResponse {
    if (!('event' in value) || value['event'] === undefined) return false;
    return true;
}

export function PXEEventResponseFromJSON(json: any): PXEEventResponse {
    return PXEEventResponseFromJSONTyped(json, false);
}

export function PXEEventResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PXEEventResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'recorded': json['recorded'] == null ? undefined : json['recorded'],
        'event': PXEBootEventFromJSON(json['event']),
    };
}

export function PXEEventResponseToJSON(json: any): PXEEventResponse {
    return PXEEventResponseToJSONTyped(json, false);
}

export function PXEEventResponseToJSONTyped(value?: PXEEventResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recorded': value['recorded'],
        'event': PXEBootEventToJSON(value['event']),
    };
}

