/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Six rollback patterns defined in Issue 0041 § 4.7.
 * @export
 */
export const PXERollbackPattern = {
    Full: 'full',
    Profile: 'profile',
    Ring: 'ring',
    Site: 'site',
    Single: 'single',
    Abort: 'abort'
} as const;
export type PXERollbackPattern = typeof PXERollbackPattern[keyof typeof PXERollbackPattern];


export function instanceOfPXERollbackPattern(value: any): boolean {
    for (const key in PXERollbackPattern) {
        if (Object.prototype.hasOwnProperty.call(PXERollbackPattern, key)) {
            if (PXERollbackPattern[key as keyof typeof PXERollbackPattern] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PXERollbackPatternFromJSON(json: any): PXERollbackPattern {
    return PXERollbackPatternFromJSONTyped(json, false);
}

export function PXERollbackPatternFromJSONTyped(json: any, ignoreDiscriminator: boolean): PXERollbackPattern {
    return json as PXERollbackPattern;
}

export function PXERollbackPatternToJSON(value?: PXERollbackPattern | null): any {
    return value as any;
}

export function PXERollbackPatternToJSONTyped(value: any, ignoreDiscriminator: boolean): PXERollbackPattern {
    return value as PXERollbackPattern;
}

