/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PXERollbackPattern } from './PXERollbackPattern';
import {
    PXERollbackPatternFromJSON,
    PXERollbackPatternFromJSONTyped,
    PXERollbackPatternToJSON,
    PXERollbackPatternToJSONTyped,
} from './PXERollbackPattern';

/**
 * Operator-initiated rollback request (from Admin WebUI or CLI).
 * @export
 * @interface PXERollbackRequest
 */
export interface PXERollbackRequest {
    /**
     * 
     * @type {PXERollbackPattern}
     * @memberof PXERollbackRequest
     */
    pattern: PXERollbackPattern;
    /**
     * Reason for rollback (audit trail).
     * @type {string}
     * @memberof PXERollbackRequest
     */
    reason: string;
    /**
     * 
     * @type {string}
     * @memberof PXERollbackRequest
     */
    targetVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PXERollbackRequest
     */
    profile?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PXERollbackRequest
     */
    ring?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PXERollbackRequest
     */
    site?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PXERollbackRequest
     */
    deviceMac?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PXERollbackRequest
     */
    backupPxeIp?: string | null;
}



/**
 * Check if a given object implements the PXERollbackRequest interface.
 */
export function instanceOfPXERollbackRequest(value: object): value is PXERollbackRequest {
    if (!('pattern' in value) || value['pattern'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function PXERollbackRequestFromJSON(json: any): PXERollbackRequest {
    return PXERollbackRequestFromJSONTyped(json, false);
}

export function PXERollbackRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PXERollbackRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'pattern': PXERollbackPatternFromJSON(json['pattern']),
        'reason': json['reason'],
        'targetVersion': json['target_version'] == null ? undefined : json['target_version'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'ring': json['ring'] == null ? undefined : json['ring'],
        'site': json['site'] == null ? undefined : json['site'],
        'deviceMac': json['device_mac'] == null ? undefined : json['device_mac'],
        'backupPxeIp': json['backup_pxe_ip'] == null ? undefined : json['backup_pxe_ip'],
    };
}

export function PXERollbackRequestToJSON(json: any): PXERollbackRequest {
    return PXERollbackRequestToJSONTyped(json, false);
}

export function PXERollbackRequestToJSONTyped(value?: PXERollbackRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pattern': PXERollbackPatternToJSON(value['pattern']),
        'reason': value['reason'],
        'target_version': value['targetVersion'],
        'profile': value['profile'],
        'ring': value['ring'],
        'site': value['site'],
        'device_mac': value['deviceMac'],
        'backup_pxe_ip': value['backupPxeIp'],
    };
}

