/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for POST /api/v1/devices/registration-tokens.
 * @export
 * @interface RegistrationTokenRequest
 */
export interface RegistrationTokenRequest {
    /**
     * 
     * @type {RegistrationTokenRequestProfileEnum}
     * @memberof RegistrationTokenRequest
     */
    profile: RegistrationTokenRequestProfileEnum;
    /**
     * SHA-256 hex digest of machine-id:MAC
     * @type {string}
     * @memberof RegistrationTokenRequest
     */
    fingerprint: string;
}


/**
 * @export
 */
export const RegistrationTokenRequestProfileEnum = {
    Standard: 'standard',
    Field: 'field',
    Kiosk: 'kiosk'
} as const;
export type RegistrationTokenRequestProfileEnum = typeof RegistrationTokenRequestProfileEnum[keyof typeof RegistrationTokenRequestProfileEnum];


/**
 * Check if a given object implements the RegistrationTokenRequest interface.
 */
export function instanceOfRegistrationTokenRequest(value: object): value is RegistrationTokenRequest {
    if (!('profile' in value) || value['profile'] === undefined) return false;
    if (!('fingerprint' in value) || value['fingerprint'] === undefined) return false;
    return true;
}

export function RegistrationTokenRequestFromJSON(json: any): RegistrationTokenRequest {
    return RegistrationTokenRequestFromJSONTyped(json, false);
}

export function RegistrationTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'profile': json['profile'],
        'fingerprint': json['fingerprint'],
    };
}

export function RegistrationTokenRequestToJSON(json: any): RegistrationTokenRequest {
    return RegistrationTokenRequestToJSONTyped(json, false);
}

export function RegistrationTokenRequestToJSONTyped(value?: RegistrationTokenRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'profile': value['profile'],
        'fingerprint': value['fingerprint'],
    };
}

