/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrationTokenResponse
 */
export interface RegistrationTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof RegistrationTokenResponse
     */
    token: string;
    /**
     * 
     * @type {Date}
     * @memberof RegistrationTokenResponse
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the RegistrationTokenResponse interface.
 */
export function instanceOfRegistrationTokenResponse(value: object): value is RegistrationTokenResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function RegistrationTokenResponseFromJSON(json: any): RegistrationTokenResponse {
    return RegistrationTokenResponseFromJSONTyped(json, false);
}

export function RegistrationTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrationTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expiresAt': (new Date(json['expires_at'])),
    };
}

export function RegistrationTokenResponseToJSON(json: any): RegistrationTokenResponse {
    return RegistrationTokenResponseToJSONTyped(json, false);
}

export function RegistrationTokenResponseToJSONTyped(value?: RegistrationTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'expires_at': value['expiresAt'].toISOString(),
    };
}

