/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Provisioning payload: registers a device and its shared secret.
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    deviceId: string;
    /**
     * 
     * @type {RegisterRequestProfileEnum}
     * @memberof RegisterRequest
     */
    profile?: RegisterRequestProfileEnum;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    hostname: string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    sharedSecret: string;
}


/**
 * @export
 */
export const RegisterRequestProfileEnum = {
    Standard: 'standard',
    Field: 'field',
    Kiosk: 'kiosk'
} as const;
export type RegisterRequestProfileEnum = typeof RegisterRequestProfileEnum[keyof typeof RegisterRequestProfileEnum];


/**
 * Check if a given object implements the RegisterRequest interface.
 */
export function instanceOfRegisterRequest(value: object): value is RegisterRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    if (!('hostname' in value) || value['hostname'] === undefined) return false;
    if (!('sharedSecret' in value) || value['sharedSecret'] === undefined) return false;
    return true;
}

export function RegisterRequestFromJSON(json: any): RegisterRequest {
    return RegisterRequestFromJSONTyped(json, false);
}

export function RegisterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['device_id'],
        'profile': json['profile'] == null ? undefined : json['profile'],
        'hostname': json['hostname'],
        'sharedSecret': json['shared_secret'],
    };
}

export function RegisterRequestToJSON(json: any): RegisterRequest {
    return RegisterRequestToJSONTyped(json, false);
}

export function RegisterRequestToJSONTyped(value?: RegisterRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_id': value['deviceId'],
        'profile': value['profile'],
        'hostname': value['hostname'],
        'shared_secret': value['sharedSecret'],
    };
}

