/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServerSummary
 */
export interface ServerSummary {
    /**
     * 
     * @type {string}
     * @memberof ServerSummary
     */
    storage?: string;
    /**
     * 
     * @type {string}
     * @memberof ServerSummary
     */
    redis?: string;
    /**
     * 
     * @type {number}
     * @memberof ServerSummary
     */
    uptimeSeconds?: number;
}

/**
 * Check if a given object implements the ServerSummary interface.
 */
export function instanceOfServerSummary(value: object): value is ServerSummary {
    return true;
}

export function ServerSummaryFromJSON(json: any): ServerSummary {
    return ServerSummaryFromJSONTyped(json, false);
}

export function ServerSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServerSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'storage': json['storage'] == null ? undefined : json['storage'],
        'redis': json['redis'] == null ? undefined : json['redis'],
        'uptimeSeconds': json['uptime_seconds'] == null ? undefined : json['uptime_seconds'],
    };
}

export function ServerSummaryToJSON(json: any): ServerSummary {
    return ServerSummaryToJSONTyped(json, false);
}

export function ServerSummaryToJSONTyped(value?: ServerSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'storage': value['storage'],
        'redis': value['redis'],
        'uptime_seconds': value['uptimeSeconds'],
    };
}

