/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenRotateResponse
 */
export interface TokenRotateResponse {
    /**
     * 
     * @type {string}
     * @memberof TokenRotateResponse
     */
    token: string;
    /**
     * 
     * @type {Date}
     * @memberof TokenRotateResponse
     */
    expiresAt: Date;
}

/**
 * Check if a given object implements the TokenRotateResponse interface.
 */
export function instanceOfTokenRotateResponse(value: object): value is TokenRotateResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    if (!('expiresAt' in value) || value['expiresAt'] === undefined) return false;
    return true;
}

export function TokenRotateResponseFromJSON(json: any): TokenRotateResponse {
    return TokenRotateResponseFromJSONTyped(json, false);
}

export function TokenRotateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRotateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
        'expiresAt': (new Date(json['expires_at'])),
    };
}

export function TokenRotateResponseToJSON(json: any): TokenRotateResponse {
    return TokenRotateResponseToJSONTyped(json, false);
}

export function TokenRotateResponseToJSONTyped(value?: TokenRotateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'expires_at': value['expiresAt'].toISOString(),
    };
}

