/* tslint:disable */
/* eslint-disable */
/**
 * cdx-server
 * Construction DX OS central platform API (Phase 1).
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Body for POST /api/v1/auth/rotate.
 * @export
 * @interface TokenRotateRequest
 */
export interface TokenRotateRequest {
    /**
     * 
     * @type {string}
     * @memberof TokenRotateRequest
     */
    deviceId: string;
}

/**
 * Check if a given object implements the TokenRotateRequest interface.
 */
export function instanceOfTokenRotateRequest(value: object): value is TokenRotateRequest {
    if (!('deviceId' in value) || value['deviceId'] === undefined) return false;
    return true;
}

export function TokenRotateRequestFromJSON(json: any): TokenRotateRequest {
    return TokenRotateRequestFromJSONTyped(json, false);
}

export function TokenRotateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenRotateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'deviceId': json['device_id'],
    };
}

export function TokenRotateRequestToJSON(json: any): TokenRotateRequest {
    return TokenRotateRequestToJSONTyped(json, false);
}

export function TokenRotateRequestToJSONTyped(value?: TokenRotateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'device_id': value['deviceId'],
    };
}

