/**
 * AUTO-GENERATED by `pnpm run sdk:gen` (scripts/generate-sdk.ts) — DO NOT EDIT.
 * Source: docs/openapi.yaml (produced by `pnpm run openapi:gen`).
 */

import type * as Types from "./types.ts";

export interface ClientOptions {
  /** Base URL of the CEOP API, e.g. "http://localhost:3000". */
  readonly baseUrl: string;
  /** Bearer credential — either a JWT from /api/v1/auth/token or a raw "keyId:secret" API key. */
  readonly token?: string;
  /** Override for testing; defaults to the global fetch. */
  readonly fetchImpl?: typeof fetch;
}

/** Thrown when the API responds with a non-2xx status. */
export class ApiError extends Error {
  readonly status: number;
  readonly body: unknown;

  constructor(status: number, body: unknown) {
    super(`CEOP API request failed with status ${status}`);
    this.name = "ApiError";
    this.status = status;
    this.body = body;
  }
}

interface RequestInit_ {
  readonly query?: Record<string, string | number | boolean | undefined>;
  readonly body?: unknown;
}

/** Typed fetch client for the Construction Enterprise Operating Platform API. */
export class CeopClient {
  private readonly baseUrl: string;
  private readonly token: string | undefined;
  private readonly fetchImpl: typeof fetch;

  constructor(options: ClientOptions) {
    this.baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.token = options.token;
    this.fetchImpl = options.fetchImpl ?? fetch;
  }

  private async request<T>(method: string, path: string, init: RequestInit_ = {}): Promise<T> {
    const url = new URL(this.baseUrl + path);
    if (init.query) {
      for (const [key, value] of Object.entries(init.query)) {
        if (value !== undefined) url.searchParams.set(key, String(value));
      }
    }

    const headers: Record<string, string> = { Accept: "application/json" };
    if (this.token) headers.Authorization = `Bearer ${this.token}`;

    const requestInit: RequestInit = { method, headers };
    if (init.body !== undefined) {
      headers["Content-Type"] = "application/json";
      requestInit.body = JSON.stringify(init.body);
    }

    const response = await this.fetchImpl(url, requestInit);

    if (response.status === 204) {
      return undefined as T;
    }

    const contentType = response.headers.get("content-type") ?? "";
    const payload: unknown = contentType.includes("application/json")
      ? await response.json()
      : await response.text();

    if (!response.ok) {
      throw new ApiError(response.status, payload);
    }
    return payload as T;
  }

  getHealth(): Promise<{ status?: string; }> {
    return this.request("GET", `/health`);
  }

  getReady(): Promise<{ status: "ready"; storage: string; timestamp: string; }> {
    return this.request("GET", `/health/ready`);
  }

  getInfo(): Promise<{ name?: string; version?: string; environment?: string; nodeVersion?: string; }> {
    return this.request("GET", `/api/v1/info`);
  }

  issueToken(body: { credential: string; }): Promise<Types.TokenResponse> {
    return this.request("POST", `/api/v1/auth/token`, { body });
  }

  revokeToken(): Promise<{ revoked: boolean; }> {
    return this.request("POST", `/api/v1/auth/revoke`);
  }

  listApiKeys(): Promise<{ keys: Array<Types.AuthKey>; }> {
    return this.request("GET", `/api/v1/auth/keys`);
  }

  revokeApiKey(keyId: string): Promise<{ revoked: boolean; keyId: string; }> {
    return this.request("DELETE", `/api/v1/auth/keys/${encodeURIComponent(String(keyId))}`);
  }

  getDashboard(): Promise<Record<string, unknown>> {
    return this.request("GET", `/api/v1/dashboard`);
  }

  listOrganizations(query: { limit?: number; offset?: number; } = {}): Promise<{ organizations: Array<Types.Organization>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/organizations`, { query });
  }

  createOrganization(body: { name: string; type: "headquarters" | "branch" | "site" | "partner"; parentId?: string; status?: "active" | "suspended" | "archived"; }): Promise<Types.Organization> {
    return this.request("POST", `/api/v1/organizations`, { body });
  }

  getOrganization(id: string): Promise<Types.Organization> {
    return this.request("GET", `/api/v1/organizations/${encodeURIComponent(String(id))}`);
  }

  updateOrganization(id: string, body: { name?: string; status?: "active" | "suspended" | "archived"; }): Promise<Types.Organization> {
    return this.request("PUT", `/api/v1/organizations/${encodeURIComponent(String(id))}`, { body });
  }

  deleteOrganization(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/organizations/${encodeURIComponent(String(id))}`);
  }

  listUsers(query: { limit?: number; offset?: number; } = {}): Promise<{ users: Array<Types.User>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/users`, { query });
  }

  createUser(body: { organizationId: string; displayName: string; email: string; status?: "invited" | "active" | "suspended" | "deactivated"; roleIds?: Array<string>; }): Promise<Types.User> {
    return this.request("POST", `/api/v1/users`, { body });
  }

  getUser(id: string): Promise<Types.User> {
    return this.request("GET", `/api/v1/users/${encodeURIComponent(String(id))}`);
  }

  updateUser(id: string, body: { displayName?: string; status?: "invited" | "active" | "suspended" | "deactivated"; roleIds?: Array<string>; }): Promise<Types.User> {
    return this.request("PUT", `/api/v1/users/${encodeURIComponent(String(id))}`, { body });
  }

  deleteUser(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/users/${encodeURIComponent(String(id))}`);
  }

  listRoles(query: { limit?: number; offset?: number; } = {}): Promise<{ roles: Array<Types.Role>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/roles`, { query });
  }

  createRole(body: { name: string; description?: string; scope: "global" | "organization" | "site"; permissions: Array<string>; }): Promise<Types.Role> {
    return this.request("POST", `/api/v1/roles`, { body });
  }

  getRole(id: string): Promise<Types.Role> {
    return this.request("GET", `/api/v1/roles/${encodeURIComponent(String(id))}`);
  }

  updateRole(id: string, body: { name?: string; description?: string; permissions?: Array<string>; }): Promise<Types.Role> {
    return this.request("PUT", `/api/v1/roles/${encodeURIComponent(String(id))}`, { body });
  }

  deleteRole(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/roles/${encodeURIComponent(String(id))}`);
  }

  listDevices(query: { limit?: number; offset?: number; } = {}): Promise<{ devices: Array<Types.Device>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/devices`, { query });
  }

  createDevice(body: { organizationId: string; kind: "tablet" | "phone" | "kiosk" | "sensor" | "laptop"; status?: "provisioned" | "active" | "lost" | "retired"; }): Promise<Types.Device> {
    return this.request("POST", `/api/v1/devices`, { body });
  }

  getDevice(id: string): Promise<Types.Device> {
    return this.request("GET", `/api/v1/devices/${encodeURIComponent(String(id))}`);
  }

  updateDevice(id: string, body: { status?: "provisioned" | "active" | "lost" | "retired"; }): Promise<Types.Device> {
    return this.request("PUT", `/api/v1/devices/${encodeURIComponent(String(id))}`, { body });
  }

  deleteDevice(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/devices/${encodeURIComponent(String(id))}`);
  }

  listApplications(query: { limit?: number; offset?: number; } = {}): Promise<{ applications: Array<Types.Application>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/applications`, { query });
  }

  createApplication(body: { key: string; name: string; category: "portal" | "governance" | "field" | "workflow" | "document"; health?: "healthy" | "degraded" | "down" | "unknown"; ownerOrganizationId: string; }): Promise<Types.Application> {
    return this.request("POST", `/api/v1/applications`, { body });
  }

  getApplication(id: string): Promise<Types.Application> {
    return this.request("GET", `/api/v1/applications/${encodeURIComponent(String(id))}`);
  }

  updateApplication(id: string, body: { name?: string; health?: "healthy" | "degraded" | "down" | "unknown"; }): Promise<Types.Application> {
    return this.request("PUT", `/api/v1/applications/${encodeURIComponent(String(id))}`, { body });
  }

  deleteApplication(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/applications/${encodeURIComponent(String(id))}`);
  }

  evaluateAccess(body: { subject: string; resource: string; action: string; attributes?: Record<string, unknown>; }): Promise<{ decision: "allow" | "deny"; matchedPolicyIds?: Array<string>; }> {
    return this.request("POST", `/api/v1/governance/evaluate`, { body });
  }

  getAuditLog(query: { limit?: number; offset?: number; } = {}): Promise<{ entries: Array<Types.AuditEntry>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/governance/audit`, { query });
  }

  exportAuditLog(query: { format?: "csv" | "json"; limit?: number; offset?: number; } = {}): Promise<{ exportedAt: string; count: number; total: number; limit: number; offset: number; entries: Array<Types.AuditEntry>; } | string> {
    return this.request("GET", `/api/v1/governance/audit/export`, { query });
  }

  verifyAuditLog(): Promise<{ valid: boolean; brokenAt?: number; checkedAt: string; }> {
    return this.request("GET", `/api/v1/governance/audit/verify`);
  }

  listPolicies(query: { limit?: number; offset?: number; } = {}): Promise<{ policies: Array<Types.Policy>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/governance/policies`, { query });
  }

  createPolicy(body: { name: string; effect: "allow" | "deny"; actions: Array<string>; resources: Array<string>; }): Promise<Types.Policy> {
    return this.request("POST", `/api/v1/governance/policies`, { body });
  }

  getPolicy(id: string): Promise<Types.Policy> {
    return this.request("GET", `/api/v1/governance/policies/${encodeURIComponent(String(id))}`);
  }

  updatePolicy(id: string, body: { name?: string; effect?: "allow" | "deny"; actions?: Array<string>; resources?: Array<string>; }): Promise<Types.Policy> {
    return this.request("PUT", `/api/v1/governance/policies/${encodeURIComponent(String(id))}`, { body });
  }

  deletePolicy(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/governance/policies/${encodeURIComponent(String(id))}`);
  }

  listWorkflows(query: { limit?: number; offset?: number; type?: "approval" | "notification" | "task"; status?: "draft" | "active" | "suspended" | "retired"; } = {}): Promise<{ workflows: Array<Types.Workflow>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/workflows`, { query });
  }

  createWorkflow(body: { name: string; type: "approval" | "notification" | "task"; status?: "draft" | "active" | "suspended" | "retired"; steps: Array<{ key: string; name: string; requiredPermission: string; }>; }): Promise<Types.Workflow> {
    return this.request("POST", `/api/v1/workflows`, { body });
  }

  getWorkflow(id: string): Promise<Types.Workflow> {
    return this.request("GET", `/api/v1/workflows/${encodeURIComponent(String(id))}`);
  }

  updateWorkflow(id: string, body: { name?: string; status?: "draft" | "active" | "suspended" | "retired"; steps?: Array<{ key: string; name: string; requiredPermission: string; }>; }): Promise<Types.Workflow> {
    return this.request("PUT", `/api/v1/workflows/${encodeURIComponent(String(id))}`, { body });
  }

  deleteWorkflow(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/workflows/${encodeURIComponent(String(id))}`);
  }

  listWorkflowInstances(query: { limit?: number; offset?: number; status?: "pending" | "approved" | "rejected" | "cancelled"; } = {}): Promise<{ workflowInstances: Array<Types.WorkflowInstance>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/workflow-instances`, { query });
  }

  createWorkflowInstance(body: { workflowId: string; subject: string; organizationId?: string; }): Promise<{ workflowInstance: Types.WorkflowInstance; }> {
    return this.request("POST", `/api/v1/workflow-instances`, { body });
  }

  decideWorkflowInstance(id: string, body: { decision: "approve" | "reject"; comment?: string; }): Promise<{ workflowInstance: Types.WorkflowInstance; }> {
    return this.request("POST", `/api/v1/workflow-instances/${encodeURIComponent(String(id))}/decision`, { body });
  }

  cancelWorkflowInstance(id: string): Promise<{ workflowInstance: Types.WorkflowInstance; }> {
    return this.request("POST", `/api/v1/workflow-instances/${encodeURIComponent(String(id))}/cancel`);
  }

  listAiActions(query: { limit?: number; offset?: number; status?: "pending" | "approved" | "rejected"; } = {}): Promise<{ aiActions: Array<Types.AiAction>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/ai-actions`, { query });
  }

  createAiAction(body: { model: string; purpose: string; promptHash: string; organizationId?: string; }): Promise<{ aiAction: Types.AiAction; }> {
    return this.request("POST", `/api/v1/ai-actions`, { body });
  }

  decideAiAction(id: string, body: { decision: "approved" | "rejected"; note?: string; }): Promise<{ aiAction: Types.AiAction; }> {
    return this.request("POST", `/api/v1/ai-actions/${encodeURIComponent(String(id))}/decision`, { body });
  }

  registerDevice(body: { id?: string; organizationId?: string; kind: "tablet" | "phone" | "kiosk" | "sensor" | "laptop"; status?: "provisioned" | "active" | "lost" | "retired"; metadata?: Record<string, string>; }): Promise<{ device: Types.Device; }> {
    return this.request("POST", `/api/v1/devices/register`, { body });
  }

  deviceHeartbeat(id: string, body?: { status?: "provisioned" | "active" | "lost" | "retired"; }): Promise<{ device: Types.Device; }> {
    return this.request("POST", `/api/v1/devices/${encodeURIComponent(String(id))}/heartbeat`, { body });
  }

  deviceInventory(id: string, body: { metadata: Record<string, string>; }): Promise<{ device: Types.Device; }> {
    return this.request("POST", `/api/v1/devices/${encodeURIComponent(String(id))}/inventory`, { body });
  }

  listProjects(query: { limit?: number; offset?: number; status?: "planning" | "in_progress" | "completed" | "suspended" | "cancelled"; } = {}): Promise<{ projects: Array<Types.Project>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects`, { query });
  }

  createProject(body: { organizationId?: string; projectCode: string; name: string; description?: string; clientName?: string; siteAddress?: string; status?: "planning" | "in_progress" | "completed" | "suspended" | "cancelled"; startDate?: string; endDate?: string; budget?: number; managerId?: string; }): Promise<{ project: Types.Project; }> {
    return this.request("POST", `/api/v1/projects`, { body });
  }

  getProject(id: string): Promise<{ project: Types.Project; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(id))}`);
  }

  deleteProject(id: string): Promise<{ deleted: boolean; }> {
    return this.request("DELETE", `/api/v1/projects/${encodeURIComponent(String(id))}`);
  }

  updateProject(id: string, body: { name?: string; description?: string; clientName?: string; siteAddress?: string; status?: "planning" | "in_progress" | "completed" | "suspended" | "cancelled"; startDate?: string; endDate?: string; budget?: number; managerId?: string; }): Promise<{ project: Types.Project; }> {
    return this.request("PATCH", `/api/v1/projects/${encodeURIComponent(String(id))}`, { body });
  }

  listDailyReports(projectId: string, query: { limit?: number; offset?: number; status?: "draft" | "submitted" | "approved"; } = {}): Promise<{ dailyReports: Array<Types.DailyReport>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/daily-reports`, { query });
  }

  createDailyReport(projectId: string, body: { reportDate: string; weather?: "sunny" | "cloudy" | "rainy" | "snowy"; temperature?: number; workerCount?: number; workContent?: string; safetyCheck?: boolean; safetyNotes?: string; progressRate?: number; issues?: string; }): Promise<{ dailyReport: Types.DailyReport; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/daily-reports`, { body });
  }

  getDailyReport(id: string): Promise<{ dailyReport: Types.DailyReport; }> {
    return this.request("GET", `/api/v1/daily-reports/${encodeURIComponent(String(id))}`);
  }

  updateDailyReport(id: string, body: { weather?: "sunny" | "cloudy" | "rainy" | "snowy"; temperature?: number; workerCount?: number; workContent?: string; safetyCheck?: boolean; safetyNotes?: string; progressRate?: number; issues?: string; }): Promise<{ dailyReport: Types.DailyReport; }> {
    return this.request("PATCH", `/api/v1/daily-reports/${encodeURIComponent(String(id))}`, { body });
  }

  transitionDailyReport(id: string, body: { status: "draft" | "submitted" | "approved"; }): Promise<{ dailyReport: Types.DailyReport; }> {
    return this.request("POST", `/api/v1/daily-reports/${encodeURIComponent(String(id))}/transition`, { body });
  }

  listPhotos(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ photos: Array<Types.Photo>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/photos`, { query });
  }

  createPhoto(projectId: string, body: { fileName: string; originalName: string; contentType: string; fileSize: number; objectKey?: string; category?: "general" | "progress" | "safety" | "quality" | "handover"; caption?: string; takenAt?: string; }): Promise<{ photo: Types.Photo; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/photos`, { body });
  }

  getPhoto(id: string): Promise<{ photo: Types.Photo; }> {
    return this.request("GET", `/api/v1/photos/${encodeURIComponent(String(id))}`);
  }

  deletePhoto(id: string): Promise<{ deleted?: boolean; }> {
    return this.request("DELETE", `/api/v1/photos/${encodeURIComponent(String(id))}`);
  }

  listSafetyChecks(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ safetyChecks: Array<Types.SafetyCheck>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/safety-checks`, { query });
  }

  createSafetyCheck(projectId: string, body: { checkDate: string; checkType?: "daily" | "patrol" | "ky" | "other"; itemsTotal?: number; itemsOk?: number; itemsNg?: number; overallResult?: "pending" | "ok" | "ng"; notes?: string; inspectorId?: string; }): Promise<{ safetyCheck: Types.SafetyCheck; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/safety-checks`, { body });
  }

  getSafetyCheck(id: string): Promise<{ safetyCheck: Types.SafetyCheck; }> {
    return this.request("GET", `/api/v1/safety-checks/${encodeURIComponent(String(id))}`);
  }

  deleteSafetyCheck(id: string): Promise<{ deleted?: boolean; }> {
    return this.request("DELETE", `/api/v1/safety-checks/${encodeURIComponent(String(id))}`);
  }

  listQualityInspections(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ qualityInspections: Array<Types.QualityInspection>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/quality-inspections`, { query });
  }

  createQualityInspection(projectId: string, body: { inspectionDate: string; inspectionType: string; targetItem: string; standardValue?: string; measuredValue?: string; result?: "pending" | "pass" | "fail"; notes?: string; inspectorId?: string; }): Promise<{ qualityInspection: Types.QualityInspection; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/quality-inspections`, { body });
  }

  getQualityInspection(id: string): Promise<{ qualityInspection: Types.QualityInspection; }> {
    return this.request("GET", `/api/v1/quality-inspections/${encodeURIComponent(String(id))}`);
  }

  deleteQualityInspection(id: string): Promise<{ deleted?: boolean; }> {
    return this.request("DELETE", `/api/v1/quality-inspections/${encodeURIComponent(String(id))}`);
  }

  listCostRecords(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ costRecords: Array<Types.CostRecord>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/cost-records`, { query });
  }

  createCostRecord(projectId: string, body: { recordDate: string; category: string; description: string; budgetedAmount?: number; actualAmount?: number; vendorName?: string; invoiceNumber?: string; notes?: string; }): Promise<{ costRecord: Types.CostRecord; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/cost-records`, { body });
  }

  getCostRecord(id: string): Promise<{ costRecord: Types.CostRecord; }> {
    return this.request("GET", `/api/v1/cost-records/${encodeURIComponent(String(id))}`);
  }

  deleteCostRecord(id: string): Promise<{ deleted?: boolean; }> {
    return this.request("DELETE", `/api/v1/cost-records/${encodeURIComponent(String(id))}`);
  }

  listWorkHours(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ workHours: Array<Types.WorkHour>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/work-hours`, { query });
  }

  createWorkHour(projectId: string, body: { workerId?: string; workDate: string; hours: number; workType?: string; notes?: string; }): Promise<{ workHour: Types.WorkHour; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/work-hours`, { body });
  }

  getWorkHour(id: string): Promise<{ workHour: Types.WorkHour; }> {
    return this.request("GET", `/api/v1/work-hours/${encodeURIComponent(String(id))}`);
  }

  listNotifications(query: { limit?: number; offset?: number; status?: "pending" | "sent" | "failed" | "retry"; } = {}): Promise<{ notifications: Array<Types.NotificationDelivery>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/notifications`, { query });
  }

  createNotification(body: { organizationId?: string; userId: string; eventKey: string; channel: "email" | "slack" | "webhook"; subject?: string; bodyPreview?: string; }): Promise<{ notification: Types.NotificationDelivery; }> {
    return this.request("POST", `/api/v1/notifications`, { body });
  }

  getNotification(id: string): Promise<{ notification: Types.NotificationDelivery; }> {
    return this.request("GET", `/api/v1/notifications/${encodeURIComponent(String(id))}`);
  }

  listKnowledge(query: { limit?: number; offset?: number; category?: "general" | "faq" | "incident" | "contract" | "safety"; q?: string; } = {}): Promise<{ knowledgeArticles: Array<Types.KnowledgeArticle>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/knowledge`, { query });
  }

  createKnowledge(body: { organizationId?: string; title: string; content: string; category?: "general" | "faq" | "incident" | "contract" | "safety"; tags?: Array<string>; isPublished?: boolean; aiGenerated?: boolean; aiActionId?: string; }): Promise<{ knowledgeArticle: Types.KnowledgeArticle; }> {
    return this.request("POST", `/api/v1/knowledge`, { body });
  }

  getKnowledge(id: string): Promise<{ knowledgeArticle: Types.KnowledgeArticle; }> {
    return this.request("GET", `/api/v1/knowledge/${encodeURIComponent(String(id))}`);
  }

  deleteKnowledge(id: string): Promise<{ deleted?: boolean; }> {
    return this.request("DELETE", `/api/v1/knowledge/${encodeURIComponent(String(id))}`);
  }

  listContracts(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ contracts: Array<Types.Contract>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/contracts`, { query });
  }

  createContract(projectId: string, body: { contractType?: "prime" | "subcontract" | "other"; contractNumber: string; title: string; party?: string; periodStart?: string; periodEnd?: string; amount?: number; description?: string; documentUrl?: string; aiRiskScore?: "pending" | "low" | "medium" | "high"; status?: "draft" | "active" | "completed" | "terminated"; }): Promise<{ contract: Types.Contract; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/contracts`, { body });
  }

  getContract(id: string): Promise<{ contract: Types.Contract; }> {
    return this.request("GET", `/api/v1/contracts/${encodeURIComponent(String(id))}`);
  }

  listAllWorkOrders(query: { limit?: number; offset?: number; } = {}): Promise<{ workOrders: Array<Types.WorkOrder>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/work-orders`, { query });
  }

  listAllInspections(query: { limit?: number; offset?: number; } = {}): Promise<{ inspections: Array<Types.Inspection>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/inspections`, { query });
  }

  listWorkOrders(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ workOrders: Array<Types.WorkOrder>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/work-orders`, { query });
  }

  createWorkOrder(projectId: string, body: { title: string; description?: string; status?: "pending" | "in_progress" | "completed" | "cancelled"; dueDate?: string; assigneeId?: string; }): Promise<{ workOrder: Types.WorkOrder; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/work-orders`, { body });
  }

  getWorkOrder(id: string): Promise<{ workOrder: Types.WorkOrder; }> {
    return this.request("GET", `/api/v1/work-orders/${encodeURIComponent(String(id))}`);
  }

  updateWorkOrder(id: string, body: { title?: string; description?: string; status?: "pending" | "in_progress" | "completed" | "cancelled"; dueDate?: string; completedAt?: string; assigneeId?: string; }): Promise<{ workOrder: Types.WorkOrder; }> {
    return this.request("PUT", `/api/v1/work-orders/${encodeURIComponent(String(id))}`, { body });
  }

  deleteWorkOrder(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/work-orders/${encodeURIComponent(String(id))}`);
  }

  listInspections(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ inspections: Array<Types.Inspection>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/inspections`, { query });
  }

  createInspection(projectId: string, body: { title: string; description?: string; inspectedAt?: string; inspectorId?: string; checklistItems?: Array<{ label: string; passed: boolean; }>; }): Promise<{ inspection: Types.Inspection; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/inspections`, { body });
  }

  getInspection(id: string): Promise<{ inspection: Types.Inspection; }> {
    return this.request("GET", `/api/v1/inspections/${encodeURIComponent(String(id))}`);
  }

  updateInspection(id: string, body: { title?: string; description?: string; inspectedAt?: string; inspectorId?: string; checklistItems?: Array<{ label: string; passed: boolean; }>; }): Promise<{ inspection: Types.Inspection; }> {
    return this.request("PUT", `/api/v1/inspections/${encodeURIComponent(String(id))}`, { body });
  }

  deleteInspection(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/inspections/${encodeURIComponent(String(id))}`);
  }

  listSupplierEvaluations(query: { limit?: number; offset?: number; } = {}): Promise<{ supplierEvaluations: Array<Types.SupplierEvaluation>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/supplier-evaluations`, { query });
  }

  createSupplierEvaluation(body: { organizationId?: string; supplierName: string; supplierCode?: string; category?: string; status?: "pending" | "approved" | "conditional" | "rejected"; evaluationDate: string; nextEvaluationDate?: string; score?: number; isoClause?: string; notes?: string; evaluatorId?: string; }): Promise<{ supplierEvaluation: Types.SupplierEvaluation; }> {
    return this.request("POST", `/api/v1/supplier-evaluations`, { body });
  }

  getSupplierEvaluation(id: string): Promise<{ supplierEvaluation: Types.SupplierEvaluation; }> {
    return this.request("GET", `/api/v1/supplier-evaluations/${encodeURIComponent(String(id))}`);
  }

  updateSupplierEvaluation(id: string, body: { supplierName?: string; supplierCode?: string; category?: string; status?: "pending" | "approved" | "conditional" | "rejected"; evaluationDate?: string; nextEvaluationDate?: string; score?: number; isoClause?: string; notes?: string; evaluatorId?: string; }): Promise<{ supplierEvaluation: Types.SupplierEvaluation; }> {
    return this.request("PUT", `/api/v1/supplier-evaluations/${encodeURIComponent(String(id))}`, { body });
  }

  deleteSupplierEvaluation(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/supplier-evaluations/${encodeURIComponent(String(id))}`);
  }

  listQualityObjectives(query: { limit?: number; offset?: number; } = {}): Promise<{ qualityObjectives: Array<Types.QualityObjective>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/quality-objectives`, { query });
  }

  createQualityObjective(body: { organizationId?: string; title: string; description?: string; isoClause?: string; target?: string; unit?: string; baseline?: number; targetValue?: number; status?: "active" | "achieved" | "cancelled"; dueDate?: string; ownerId?: string; }): Promise<{ qualityObjective: Types.QualityObjective; }> {
    return this.request("POST", `/api/v1/quality-objectives`, { body });
  }

  getQualityObjective(id: string): Promise<{ qualityObjective: Types.QualityObjective; }> {
    return this.request("GET", `/api/v1/quality-objectives/${encodeURIComponent(String(id))}`);
  }

  updateQualityObjective(id: string, body: { title?: string; description?: string; isoClause?: string; target?: string; unit?: string; baseline?: number; targetValue?: number; status?: "active" | "achieved" | "cancelled"; dueDate?: string; ownerId?: string; }): Promise<{ qualityObjective: Types.QualityObjective; }> {
    return this.request("PUT", `/api/v1/quality-objectives/${encodeURIComponent(String(id))}`, { body });
  }

  deleteQualityObjective(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/quality-objectives/${encodeURIComponent(String(id))}`);
  }

  listRisks(query: { limit?: number; offset?: number; } = {}): Promise<{ risks: Array<Types.Risk>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/risks`, { query });
  }

  createRisk(body: { organizationId?: string; objectiveId?: string; title: string; description?: string; isoClause?: string; likelihood?: number; impact?: number; riskLevel?: "very_low" | "low" | "medium" | "high" | "very_high"; status?: "identified" | "assessed" | "mitigated" | "accepted" | "closed"; treatmentPlan?: string; residualRisk?: string; ownerId?: string; reviewDate?: string; }): Promise<{ risk: Types.Risk; }> {
    return this.request("POST", `/api/v1/risks`, { body });
  }

  getRisk(id: string): Promise<{ risk: Types.Risk; }> {
    return this.request("GET", `/api/v1/risks/${encodeURIComponent(String(id))}`);
  }

  updateRisk(id: string, body: { title?: string; description?: string; isoClause?: string; likelihood?: number; impact?: number; riskLevel?: "very_low" | "low" | "medium" | "high" | "very_high"; status?: "identified" | "assessed" | "mitigated" | "accepted" | "closed"; treatmentPlan?: string; residualRisk?: string; ownerId?: string; reviewDate?: string; }): Promise<{ risk: Types.Risk; }> {
    return this.request("PUT", `/api/v1/risks/${encodeURIComponent(String(id))}`, { body });
  }

  deleteRisk(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/risks/${encodeURIComponent(String(id))}`);
  }

  listManagementReviews(query: { limit?: number; offset?: number; } = {}): Promise<{ managementReviews: Array<Types.ManagementReview>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/management-reviews`, { query });
  }

  createManagementReview(body: { organizationId?: string; title: string; status?: "scheduled" | "in_progress" | "completed" | "cancelled"; reviewDate: string; nextReviewDate?: string; agenda?: string; outcomes?: string; isoClause?: string; facilitatorId?: string; }): Promise<{ managementReview: Types.ManagementReview; }> {
    return this.request("POST", `/api/v1/management-reviews`, { body });
  }

  getManagementReview(id: string): Promise<{ managementReview: Types.ManagementReview; }> {
    return this.request("GET", `/api/v1/management-reviews/${encodeURIComponent(String(id))}`);
  }

  updateManagementReview(id: string, body: { title?: string; status?: "scheduled" | "in_progress" | "completed" | "cancelled"; reviewDate?: string; nextReviewDate?: string; agenda?: string; outcomes?: string; isoClause?: string; facilitatorId?: string; }): Promise<{ managementReview: Types.ManagementReview; }> {
    return this.request("PUT", `/api/v1/management-reviews/${encodeURIComponent(String(id))}`, { body });
  }

  deleteManagementReview(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/management-reviews/${encodeURIComponent(String(id))}`);
  }

  listAiBuildProjects(query: { limit?: number; offset?: number; } = {}): Promise<{ aiBuildProjects: Array<Types.AiBuildProject>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/ai-build-projects`, { query });
  }

  createAiBuildProject(body: { organizationId?: string; projectId?: string; name: string; theme: string; purpose?: string; scope?: string; targetUsers?: string; templateVersion?: string; status?: "generated" | "archived" | "restored" | "deleted"; placeholderChecked?: boolean; }): Promise<{ aiBuildProject: Types.AiBuildProject; }> {
    return this.request("POST", `/api/v1/ai-build-projects`, { body });
  }

  getAiBuildProject(id: string): Promise<{ aiBuildProject: Types.AiBuildProject; }> {
    return this.request("GET", `/api/v1/ai-build-projects/${encodeURIComponent(String(id))}`);
  }

  updateAiBuildProject(id: string, body: { name?: string; theme?: string; purpose?: string; scope?: string; targetUsers?: string; templateVersion?: string; status?: "generated" | "archived" | "restored" | "deleted"; placeholderChecked?: boolean; }): Promise<{ aiBuildProject: Types.AiBuildProject; }> {
    return this.request("PUT", `/api/v1/ai-build-projects/${encodeURIComponent(String(id))}`, { body });
  }

  deleteAiBuildProject(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/ai-build-projects/${encodeURIComponent(String(id))}`);
  }

  listDxProjects(query: { limit?: number; offset?: number; } = {}): Promise<{ dxProjects: Array<Types.DxProject>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/dx-projects`, { query });
  }

  createDxProject(body: { organizationId?: string; slug: string; nameJa: string; nameEn?: string; shortName?: string; summary?: string; portfolioType?: "internal" | "external" | "common" | "unclassified"; companyAssetUse?: "yes" | "no" | "review"; domainCode?: string; lifecycleState?: "planning" | "requirements" | "development" | "verification" | "production_ready" | "production" | "paused" | "merging" | "retired" | "deleted"; importance?: number; ownerTeam?: string; approvedProgress?: number; progressMilestone?: string; progressEvidenceUrl?: string; nextReviewAt?: string; }): Promise<{ dxProject: Types.DxProject; }> {
    return this.request("POST", `/api/v1/dx-projects`, { body });
  }

  getDxProject(id: string): Promise<{ dxProject: Types.DxProject; }> {
    return this.request("GET", `/api/v1/dx-projects/${encodeURIComponent(String(id))}`);
  }

  updateDxProject(id: string, body: { nameJa?: string; nameEn?: string; shortName?: string; summary?: string; portfolioType?: "internal" | "external" | "common" | "unclassified"; companyAssetUse?: "yes" | "no" | "review"; domainCode?: string; lifecycleState?: "planning" | "requirements" | "development" | "verification" | "production_ready" | "production" | "paused" | "merging" | "retired" | "deleted"; importance?: number; ownerTeam?: string; approvedProgress?: number; progressMilestone?: string; progressEvidenceUrl?: string; nextReviewAt?: string; }): Promise<{ dxProject: Types.DxProject; }> {
    return this.request("PUT", `/api/v1/dx-projects/${encodeURIComponent(String(id))}`, { body });
  }

  deleteDxProject(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/dx-projects/${encodeURIComponent(String(id))}`);
  }

  listMaterialPhotoLogs(query: { limit?: number; offset?: number; } = {}): Promise<{ materialPhotoLogs: Array<Types.MaterialPhotoLog>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/material-photo-logs`, { query });
  }

  createMaterialPhotoLog(body: { organizationId?: string; projectCode: string; materialName: string; materialCategory?: string; quantity?: number; unit?: string; storagePlace?: string; memo?: string; transactionType?: "received" | "placed" | "used" | "returned"; inspectionStatus?: "pending" | "passed" | "failed" | "review"; needsReview?: boolean; capturedAt?: string; latitude?: number; longitude?: number; objectKey?: string; }): Promise<{ materialPhotoLog: Types.MaterialPhotoLog; }> {
    return this.request("POST", `/api/v1/material-photo-logs`, { body });
  }

  exportMaterialPhotoLogsCsv(): Promise<string> {
    return this.request("GET", `/api/v1/material-photo-logs/export.csv`);
  }

  getMaterialPhotoLog(id: string): Promise<{ materialPhotoLog: Types.MaterialPhotoLog; }> {
    return this.request("GET", `/api/v1/material-photo-logs/${encodeURIComponent(String(id))}`);
  }

  updateMaterialPhotoLog(id: string, body: { materialName?: string; materialCategory?: string; quantity?: number; unit?: string; storagePlace?: string; memo?: string; transactionType?: "received" | "placed" | "used" | "returned"; inspectionStatus?: "pending" | "passed" | "failed" | "review"; needsReview?: boolean; capturedAt?: string; latitude?: number; longitude?: number; objectKey?: string; }): Promise<{ materialPhotoLog: Types.MaterialPhotoLog; }> {
    return this.request("PUT", `/api/v1/material-photo-logs/${encodeURIComponent(String(id))}`, { body });
  }

  deleteMaterialPhotoLog(id: string): Promise<void> {
    return this.request("DELETE", `/api/v1/material-photo-logs/${encodeURIComponent(String(id))}`);
  }

  listItsmIncidents(): Promise<{ incidents?: Array<Record<string, unknown>>; }> {
    return this.request("GET", `/api/v1/itsm/incidents`);
  }

  createItsmIncident(body: { title: string; severity: "low" | "medium" | "high" | "critical"; }): Promise<{ incident?: Record<string, unknown>; }> {
    return this.request("POST", `/api/v1/itsm/incidents`, { body });
  }

  getItsmIncident(id: string): Promise<{ incident?: Record<string, unknown>; }> {
    return this.request("GET", `/api/v1/itsm/incidents/${encodeURIComponent(String(id))}`);
  }

  listDocuments(query: { limit?: number; offset?: number; type?: "drawing" | "contract" | "safety" | "quality" | "other"; } = {}): Promise<{ documents: Array<Types.Document>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/documents`, { query });
  }

  createDocument(body: { organizationId?: string; projectId?: string; title: string; documentType?: "drawing" | "contract" | "safety" | "quality" | "other"; revision?: number; status?: "draft" | "review" | "approved" | "issued" | "archived"; fileUrl?: string; fileSize?: number; }): Promise<{ document: Types.Document; }> {
    return this.request("POST", `/api/v1/documents`, { body });
  }

  getDocument(id: string): Promise<{ document: Types.Document; }> {
    return this.request("GET", `/api/v1/documents/${encodeURIComponent(String(id))}`);
  }

  deleteDocument(id: string): Promise<{ deleted?: boolean; }> {
    return this.request("DELETE", `/api/v1/documents/${encodeURIComponent(String(id))}`);
  }

  listWorkSchedules(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ workSchedules: Array<Types.WorkSchedule>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/work-schedules`, { query });
  }

  createWorkSchedule(projectId: string, body: { workDate: string; title: string; assignee?: string; status?: "planned" | "in_progress" | "completed" | "cancelled"; notes?: string; }): Promise<{ workSchedule: Types.WorkSchedule; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/work-schedules`, { body });
  }

  getWorkSchedule(id: string): Promise<{ workSchedule: Types.WorkSchedule; }> {
    return this.request("GET", `/api/v1/work-schedules/${encodeURIComponent(String(id))}`);
  }

  listPurchaseOrders(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ purchaseOrders: Array<Types.PurchaseOrder>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/purchase-orders`, { query });
  }

  createPurchaseOrder(projectId: string, body: { orderNumber: string; supplier: string; item: string; quantity: number; unitPrice: number; status?: "draft" | "issued" | "approved" | "received" | "cancelled"; notes?: string; }): Promise<{ purchaseOrder: Types.PurchaseOrder; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/purchase-orders`, { body });
  }

  getPurchaseOrder(id: string): Promise<{ purchaseOrder: Types.PurchaseOrder; }> {
    return this.request("GET", `/api/v1/purchase-orders/${encodeURIComponent(String(id))}`);
  }

  getNotificationPreference(userId: string): Promise<{ notificationPreference: Types.NotificationPreference; }> {
    return this.request("GET", `/api/v1/notification-preferences/${encodeURIComponent(String(userId))}`);
  }

  upsertNotificationPreference(userId: string, body: { emailEnabled?: boolean; slackEnabled?: boolean; slackWebhookUrl?: string; events?: Record<string, boolean>; }): Promise<{ notificationPreference: Types.NotificationPreference; }> {
    return this.request("PUT", `/api/v1/notification-preferences/${encodeURIComponent(String(userId))}`, { body });
  }

  listComplianceChecks(projectId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ complianceChecks: Array<Types.ComplianceCheck>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/projects/${encodeURIComponent(String(projectId))}/compliance-checks`, { query });
  }

  createComplianceCheck(projectId: string, body: { standard?: "kensetsugyo-ho" | "shitauke-ho" | "iso-9001" | "iso-14001" | "iso-45001" | "other"; item: string; result?: "pass" | "fail" | "pending"; checkedAt?: string; notes?: string; }): Promise<{ complianceCheck: Types.ComplianceCheck; }> {
    return this.request("POST", `/api/v1/projects/${encodeURIComponent(String(projectId))}/compliance-checks`, { body });
  }

  getComplianceCheck(id: string): Promise<{ complianceCheck: Types.ComplianceCheck; }> {
    return this.request("GET", `/api/v1/compliance-checks/${encodeURIComponent(String(id))}`);
  }

  listLegalEvidence(contractId: string, query: { limit?: number; offset?: number; } = {}): Promise<{ legalEvidence: Array<Types.LegalEvidence>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/contracts/${encodeURIComponent(String(contractId))}/legal-evidence`, { query });
  }

  createLegalEvidence(contractId: string, body: { eventType: string; description: string; evidenceHash?: string; occurredAt?: string; }): Promise<{ legalEvidence: Types.LegalEvidence; }> {
    return this.request("POST", `/api/v1/contracts/${encodeURIComponent(String(contractId))}/legal-evidence`, { body });
  }

  getLegalEvidence(id: string): Promise<{ legalEvidence: Types.LegalEvidence; }> {
    return this.request("GET", `/api/v1/legal-evidence/${encodeURIComponent(String(id))}`);
  }

  listNotificationTemplates(query: { limit?: number; offset?: number; channel?: "email" | "slack" | "webhook"; } = {}): Promise<{ notificationTemplates: Array<Types.NotificationTemplate>; count: number; total: number; limit: number; offset: number; }> {
    return this.request("GET", `/api/v1/notification-templates`, { query });
  }

  createNotificationTemplate(body: { templateKey: string; subject: string; body: string; channel?: "email" | "slack" | "webhook"; }): Promise<{ notificationTemplate: Types.NotificationTemplate; }> {
    return this.request("POST", `/api/v1/notification-templates`, { body });
  }

  getNotificationTemplate(id: string): Promise<{ notificationTemplate: Types.NotificationTemplate; }> {
    return this.request("GET", `/api/v1/notification-templates/${encodeURIComponent(String(id))}`);
  }

  getUnreadNotificationCount(): Promise<{ unreadCount: number; }> {
    return this.request("GET", `/api/v1/notifications/unread-count`);
  }

  markNotificationRead(id: string): Promise<{ notification: Types.NotificationDelivery; }> {
    return this.request("PATCH", `/api/v1/notifications/${encodeURIComponent(String(id))}/read`);
  }

  gatewayGet(service: string, proxyPath: string): Promise<Record<string, unknown>> {
    return this.request("GET", `/api/v1/integrations/${encodeURIComponent(String(service))}/${encodeURIComponent(String(proxyPath))}`);
  }

  gatewayPut(service: string, proxyPath: string): Promise<Record<string, unknown>> {
    return this.request("PUT", `/api/v1/integrations/${encodeURIComponent(String(service))}/${encodeURIComponent(String(proxyPath))}`);
  }

  gatewayPost(service: string, proxyPath: string): Promise<Record<string, unknown>> {
    return this.request("POST", `/api/v1/integrations/${encodeURIComponent(String(service))}/${encodeURIComponent(String(proxyPath))}`);
  }

  gatewayDelete(service: string, proxyPath: string): Promise<Record<string, unknown>> {
    return this.request("DELETE", `/api/v1/integrations/${encodeURIComponent(String(service))}/${encodeURIComponent(String(proxyPath))}`);
  }

  gatewayPatch(service: string, proxyPath: string): Promise<Record<string, unknown>> {
    return this.request("PATCH", `/api/v1/integrations/${encodeURIComponent(String(service))}/${encodeURIComponent(String(proxyPath))}`);
  }
}
