/**
 * AUTO-GENERATED by `pnpm run sdk:gen` (scripts/generate-sdk.ts) — DO NOT EDIT.
 * Source: docs/openapi.yaml (produced by `pnpm run openapi:gen`).
 */

export interface ErrorResponse {
  error: string;
  message?: string;
  details?: Record<string, unknown>;
}

export interface PaginationMeta {
  count: number;
  total: number;
  limit: number;
  offset: number;
}

export interface Organization {
  id: string;
  name: string;
  type: "headquarters" | "branch" | "site" | "partner";
  status: "active" | "suspended" | "archived";
  parentId?: string;
  createdAt: string;
}

export interface User {
  id: string;
  organizationId: string;
  displayName: string;
  email: string;
  status: "invited" | "active" | "suspended" | "deactivated";
  roleIds: Array<string>;
  createdAt: string;
}

export interface Role {
  id: string;
  name: string;
  description?: string;
  scope: "global" | "organization" | "site";
  permissions: Array<string>;
}

export interface Device {
  id: string;
  organizationId: string;
  kind: "tablet" | "phone" | "kiosk" | "sensor" | "laptop";
  status: "provisioned" | "active" | "lost" | "retired";
  assignedUserId?: string;
  lastSeenAt?: string;
  metadata?: Record<string, string>;
}

export interface Application {
  id: string;
  key: string;
  name: string;
  category: "portal" | "governance" | "field" | "workflow" | "document";
  health: "healthy" | "degraded" | "down" | "unknown";
  ownerOrganizationId: string;
}

export interface Policy {
  id: string;
  name: string;
  effect: "allow" | "deny";
  actions: Array<string>;
  resources: Array<string>;
}

export interface Workflow {
  id: string;
  name: string;
  type: "approval" | "notification" | "task";
  status: "draft" | "active" | "suspended" | "retired";
  steps: Array<{ key: string;
  name: string;
  requiredPermission: string;
  }>;
}

export interface WorkflowInstance {
  id: string;
  workflowId: string;
  organizationId: string;
  subject: string;
  stepKey: string;
  stepName: string;
  status: "pending" | "approved" | "rejected" | "cancelled";
  requestedAt: string;
  decidedAt?: string;
  decidedBy?: string;
  decision?: "approve" | "reject";
  comment?: string;
}

export interface AiAction {
  id: string;
  requester: string;
  organizationId?: string;
  model: string;
  purpose: string;
  promptHash: string;
  status: "pending" | "approved" | "rejected";
  createdAt: string;
  updatedAt: string;
  decidedBy?: string;
  decidedAt?: string;
  decisionNote?: string;
}

export interface Project {
  id: string;
  organizationId: string;
  projectCode: string;
  name: string;
  description?: string;
  clientName?: string;
  siteAddress?: string;
  status: "planning" | "in_progress" | "completed" | "suspended" | "cancelled";
  startDate?: string;
  endDate?: string;
  budget?: number;
  managerId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface DailyReport {
  id: string;
  organizationId: string;
  projectId: string;
  reportDate: string;
  weather?: "sunny" | "cloudy" | "rainy" | "snowy";
  temperature?: number;
  workerCount: number;
  workContent?: string;
  safetyCheck: boolean;
  safetyNotes?: string;
  progressRate?: number;
  issues?: string;
  status: "draft" | "submitted" | "approved";
  createdAt: string;
  updatedAt: string;
}

export interface Photo {
  id: string;
  organizationId: string;
  projectId: string;
  fileName: string;
  originalName: string;
  contentType: string;
  fileSize: number;
  objectKey: string;
  category: "general" | "progress" | "safety" | "quality" | "handover";
  caption?: string;
  takenAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface SafetyCheck {
  id: string;
  organizationId: string;
  projectId: string;
  checkDate: string;
  checkType: "daily" | "patrol" | "ky" | "other";
  itemsTotal: number;
  itemsOk: number;
  itemsNg: number;
  overallResult: "pending" | "ok" | "ng";
  notes?: string;
  inspectorId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface QualityInspection {
  id: string;
  organizationId: string;
  projectId: string;
  inspectionDate: string;
  inspectionType: string;
  targetItem: string;
  standardValue?: string;
  measuredValue?: string;
  result: "pending" | "pass" | "fail";
  notes?: string;
  inspectorId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface CostRecord {
  id: string;
  organizationId: string;
  projectId: string;
  recordDate: string;
  category: string;
  description: string;
  budgetedAmount: number;
  actualAmount: number;
  vendorName?: string;
  invoiceNumber?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface WorkHour {
  id: string;
  organizationId: string;
  projectId: string;
  workerId?: string;
  workDate: string;
  hours: number;
  workType?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface NotificationDelivery {
  id: string;
  organizationId?: string;
  userId: string;
  eventKey: string;
  channel: "email" | "slack" | "webhook";
  status: "pending" | "sent" | "failed" | "retry";
  subject?: string;
  bodyPreview?: string;
  errorDetail?: string;
  failureKind?: string;
  attempts: number;
  sentAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface KnowledgeArticle {
  id: string;
  organizationId: string;
  title: string;
  content: string;
  category: "general" | "faq" | "incident" | "contract" | "safety";
  tags: Array<string>;
  isPublished: boolean;
  viewCount: number;
  rating?: number;
  aiGenerated: boolean;
  aiActionId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Contract {
  id: string;
  organizationId: string;
  projectId: string;
  contractType: "prime" | "subcontract" | "other";
  contractNumber: string;
  title: string;
  party?: string;
  periodStart?: string;
  periodEnd?: string;
  amount?: number;
  description?: string;
  documentUrl?: string;
  aiRiskScore: "pending" | "low" | "medium" | "high";
  status: "draft" | "active" | "completed" | "terminated";
  createdAt: string;
  updatedAt: string;
}

export interface Document {
  id: string;
  organizationId: string;
  projectId?: string;
  title: string;
  documentType: "drawing" | "contract" | "safety" | "quality" | "other";
  revision: number;
  status: "draft" | "review" | "approved" | "issued" | "archived";
  fileUrl?: string;
  fileSize?: number;
  tags: Array<string>;
  createdAt: string;
  updatedAt: string;
}

export interface WorkSchedule {
  id: string;
  organizationId: string;
  projectId: string;
  workDate: string;
  title: string;
  assignee?: string;
  status: "planned" | "in_progress" | "completed" | "cancelled";
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface PurchaseOrder {
  id: string;
  organizationId: string;
  projectId: string;
  orderNumber: string;
  supplier: string;
  item: string;
  quantity: number;
  unitPrice: number;
  amount: number;
  status: "draft" | "issued" | "approved" | "received" | "cancelled";
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface NotificationPreference {
  id: string;
  organizationId?: string;
  userId: string;
  emailEnabled: boolean;
  slackEnabled: boolean;
  slackWebhookUrl?: string;
  events: Record<string, boolean>;
  createdAt: string;
  updatedAt: string;
}

export interface ComplianceCheck {
  id: string;
  organizationId: string;
  projectId: string;
  standard: "kensetsugyo-ho" | "shitauke-ho" | "iso-9001" | "iso-14001" | "iso-45001" | "other";
  item: string;
  result: "pass" | "fail" | "pending";
  checkedAt?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface LegalEvidence {
  id: string;
  organizationId: string;
  contractId: string;
  eventType: string;
  description: string;
  evidenceHash?: string;
  occurredAt: string;
  createdAt: string;
}

export interface NotificationTemplate {
  id: string;
  organizationId?: string;
  templateKey: string;
  subject: string;
  body: string;
  channel: "email" | "slack" | "webhook";
  createdAt: string;
  updatedAt: string;
}

export interface AuditEntry {
  id: string;
  at: string;
  actor: string;
  action: string;
  resource: string;
  outcome: "success" | "failure" | "denied";
  hash: string;
  metadata?: Record<string, string>;
}

export interface TokenResponse {
  token: string;
  expiresIn: number;
  subject: string;
  organizationId?: string;
}

export interface AuthKey {
  keyId: string;
  subject: string;
  permissions: Array<string>;
  organizationId?: string;
  createdAt?: string;
}

export interface WorkOrder {
  id: string;
  organizationId: string;
  projectId: string;
  title: string;
  description?: string;
  status: "pending" | "in_progress" | "completed" | "cancelled";
  dueDate?: string;
  completedAt?: string;
  assigneeId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Inspection {
  id: string;
  organizationId: string;
  projectId: string;
  title: string;
  description?: string;
  result: "pass" | "fail" | "pending";
  inspectedAt?: string;
  inspectorId?: string;
  checklistItems: Array<{ label: string;
  passed: boolean;
  }>;
  createdAt: string;
  updatedAt: string;
}

export interface SupplierEvaluation {
  id: string;
  organizationId: string;
  supplierName: string;
  supplierCode?: string;
  category?: string;
  status: "pending" | "approved" | "conditional" | "rejected";
  evaluationDate: string;
  nextEvaluationDate?: string;
  score?: number;
  isoClause?: string;
  notes?: string;
  evaluatorId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface QualityObjective {
  id: string;
  organizationId: string;
  title: string;
  description?: string;
  isoClause?: string;
  target?: string;
  unit?: string;
  baseline?: number;
  targetValue?: number;
  status: "active" | "achieved" | "cancelled";
  dueDate?: string;
  ownerId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Risk {
  id: string;
  organizationId: string;
  objectiveId?: string;
  title: string;
  description?: string;
  isoClause?: string;
  likelihood: number;
  impact: number;
  riskLevel: "very_low" | "low" | "medium" | "high" | "very_high";
  status: "identified" | "assessed" | "mitigated" | "accepted" | "closed";
  treatmentPlan?: string;
  residualRisk?: string;
  ownerId?: string;
  reviewDate?: string;
  createdAt: string;
  updatedAt: string;
}

export interface ManagementReview {
  id: string;
  organizationId: string;
  title: string;
  status: "scheduled" | "in_progress" | "completed" | "cancelled";
  reviewDate: string;
  nextReviewDate?: string;
  agenda?: string;
  outcomes?: string;
  isoClause?: string;
  facilitatorId?: string;
  createdAt: string;
  updatedAt: string;
}

export interface AiBuildProject {
  id: string;
  organizationId: string;
  projectId?: string;
  name: string;
  theme: string;
  purpose?: string;
  scope?: string;
  targetUsers?: string;
  templateVersion: string;
  status: "generated" | "archived" | "restored" | "deleted";
  placeholderChecked: boolean;
  generatedAt: string;
  createdAt: string;
  updatedAt: string;
}

export interface DxProject {
  id: string;
  organizationId: string;
  slug: string;
  nameJa: string;
  nameEn?: string;
  shortName?: string;
  summary?: string;
  portfolioType: "internal" | "external" | "common" | "unclassified";
  companyAssetUse: "yes" | "no" | "review";
  domainCode?: string;
  lifecycleState: "planning" | "requirements" | "development" | "verification" | "production_ready" | "production" | "paused" | "merging" | "retired" | "deleted";
  importance: number;
  ownerTeam?: string;
  approvedProgress?: number;
  progressMilestone?: string;
  progressEvidenceUrl?: string;
  nextReviewAt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface MaterialPhotoLog {
  id: string;
  organizationId: string;
  projectCode: string;
  materialName: string;
  materialCategory?: string;
  quantity?: number;
  unit?: string;
  storagePlace?: string;
  memo?: string;
  transactionType: "received" | "placed" | "used" | "returned";
  inspectionStatus: "pending" | "passed" | "failed" | "review";
  needsReview: boolean;
  capturedAt?: string;
  latitude?: number;
  longitude?: number;
  objectKey?: string;
  createdAt: string;
  updatedAt: string;
}
