# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.pxe_api import PxeApi


class TestPxeApi(unittest.TestCase):
    """PxeApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PxeApi()

    def tearDown(self) -> None:
        pass

    def test_record_pxe_event_api_v1_pxe_events_post(self) -> None:
        """Test case for record_pxe_event_api_v1_pxe_events_post

        Record Pxe Event
        """
        pass

    def test_request_pxe_rollback_api_v1_pxe_rollback_post(self) -> None:
        """Test case for request_pxe_rollback_api_v1_pxe_rollback_post

        Request Pxe Rollback
        """
        pass


if __name__ == '__main__':
    unittest.main()
