# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.pxe_event_request import PXEEventRequest

class TestPXEEventRequest(unittest.TestCase):
    """PXEEventRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PXEEventRequest:
        """Test PXEEventRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PXEEventRequest`
        """
        model = PXEEventRequest()
        if include_optional:
            return PXEEventRequest(
                event = 'token_issued',
                profile = 'kiosk',
                fingerprint = '0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263',
                duration_seconds = 0.0,
                error_message = ''
            )
        else:
            return PXEEventRequest(
                event = 'token_issued',
                profile = 'kiosk',
                fingerprint = '0123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263',
        )
        """

    def testPXEEventRequest(self):
        """Test PXEEventRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
