# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.health_api import HealthApi


class TestHealthApi(unittest.TestCase):
    """HealthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HealthApi()

    def tearDown(self) -> None:
        pass

    def test_health_health_get(self) -> None:
        """Test case for health_health_get

        Health
        """
        pass

    def test_health_live_health_live_get(self) -> None:
        """Test case for health_live_health_live_get

        Health Live
        """
        pass

    def test_health_ready_health_ready_get(self) -> None:
        """Test case for health_ready_health_ready_get

        Health Ready
        """
        pass


if __name__ == '__main__':
    unittest.main()
