# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.register_request import RegisterRequest

class TestRegisterRequest(unittest.TestCase):
    """RegisterRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegisterRequest:
        """Test RegisterRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegisterRequest`
        """
        model = RegisterRequest()
        if include_optional:
            return RegisterRequest(
                device_id = 'z0',
                profile = 'standard',
                hostname = '0',
                shared_secret = '0123456789101112131415'
            )
        else:
            return RegisterRequest(
                device_id = 'z0',
                hostname = '0',
                shared_secret = '0123456789101112131415',
        )
        """

    def testRegisterRequest(self):
        """Test RegisterRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
