# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.dashboard_api import DashboardApi


class TestDashboardApi(unittest.TestCase):
    """DashboardApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DashboardApi()

    def tearDown(self) -> None:
        pass

    def test_dashboard_api_v1_dashboard_get(self) -> None:
        """Test case for dashboard_api_v1_dashboard_get

        Dashboard
        """
        pass


if __name__ == '__main__':
    unittest.main()
