# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.api.serial_scan_api import SerialScanApi


class TestSerialScanApi(unittest.TestCase):
    """SerialScanApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SerialScanApi()

    def tearDown(self) -> None:
        pass

    def test_confirm_item_api_v1_serial_confirm_item_id_post(self) -> None:
        """Test case for confirm_item_api_v1_serial_confirm_item_id_post

        Confirm Item
        """
        pass

    def test_discard_item_api_v1_serial_queue_item_id_delete(self) -> None:
        """Test case for discard_item_api_v1_serial_queue_item_id_delete

        Discard Item
        """
        pass

    def test_get_queue_api_v1_serial_queue_get(self) -> None:
        """Test case for get_queue_api_v1_serial_queue_get

        Get Queue
        """
        pass

    def test_serial_status_api_v1_serial_status_get(self) -> None:
        """Test case for serial_status_api_v1_serial_status_get

        Serial Status
        """
        pass

    def test_trigger_scan_api_v1_serial_scan_post(self) -> None:
        """Test case for trigger_scan_api_v1_serial_scan_post

        Trigger Scan
        """
        pass


if __name__ == '__main__':
    unittest.main()
