# coding: utf-8

"""
    cdx-server

    Construction DX OS central platform API (Phase 1).

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cdx_client.models.liveness_response import LivenessResponse

class TestLivenessResponse(unittest.TestCase):
    """LivenessResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LivenessResponse:
        """Test LivenessResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LivenessResponse`
        """
        model = LivenessResponse()
        if include_optional:
            return LivenessResponse(
                status = 'ok',
                service = 'cdx-server',
                version = '',
                uptime_seconds = 1.337
            )
        else:
            return LivenessResponse(
                version = '',
        )
        """

    def testLivenessResponse(self):
        """Test LivenessResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
